const NS='http://www.w3.org/2000/svg',groups=['E1','E2','E3','E4','E5'];
const features=[
 {key:'E_Holding.MP..mV.',name:'Holding MP',unit:'mV'},
 {key:'E_Input.resistance..MOhm.',name:'Input resistance',unit:'MΩ'},
 {key:'E_Membrane.time.constant..ms.',name:'Membrane tau',unit:'ms'},
 {key:'E_Rheobase..pA.',name:'Rheobase',unit:'pA'},
 {key:'E_Sag.ratio',name:'Sag ratio',unit:'ratio'},
 {key:'E_Sag.time..s.',name:'Sag time',unit:'s'},
 {key:'E_AP.threshold..mV.',name:'AP threshold',unit:'mV'},
 {key:'E_Max.number.of.APs',name:'Max APs',unit:'count'},
 {key:'E_Afterhyperpolarization..mV.',name:'AHP',unit:'mV'},
 {key:'E_AP.amplitude.adaptation.index',name:'AP amplitude adaptation',unit:'index'},
 {key:'E_AP.amplitude..mV.',name:'AP amplitude',unit:'mV'},
 {key:'E_AP.width..ms.',name:'AP width',unit:'ms'},
 {key:'E_Upstroke.to.downstroke.ratio',name:'Up/down ratio',unit:'ratio'},
 {key:'E_Latency..ms.',name:'Latency',unit:'ms'},
 {key:'E_Latency....20pA.current..ms.',name:'Latency @ +20 pA',unit:'ms'},
 {key:'E_ISI.adaptation.index',name:'ISI adaptation',unit:'index'},
 {key:'E_ISI.coefficient.of.variation',name:'ISI CV',unit:'CV'},
 {key:'E_AP.coefficient.of.variation',name:'AP CV',unit:'CV'}
];
const core6=['E_Input.resistance..MOhm.','E_Membrane.time.constant..ms.','E_Rheobase..pA.','E_Max.number.of.APs','E_Afterhyperpolarization..mV.','E_AP.amplitude.adaptation.index'],counts={E1:142,E2:160,E3:45,E4:61,E5:42};
const defaults={pairLayout:'stacked',pairGap:14,uniformYAxisHeight:true,statsAspectRatio:0,columns:3,panelWidth:420,panelHeight:620,panelGapX:12,panelGapY:18,canvasColor:'#ffffff',showPanelTitles:false,panelTitleSize:7,showPoints:true,pointSize:2.8,pointOpacity:.5,jitterWidth:.3,showBoxes:true,boxWidth:.48,boxLineWidth:.55,boxFillOpacity:.1,whiskerWidth:.28,medianLineWidth:.7,showP:true,pSource:'P_adj_Holm_within_feature',pCutoff:.05,pFontSize:5,pLineWidth:.4,pRowGap:13,pLabelGap:3,pNotation:'scientific',showOmnibus:false,showAxes:true,showTicks:true,showTickLabels:true,showXLabels:true,showYLabels:true,axisLineWidth:.6,tickLength:4,tickCount:4,axisFontSize:6,yLabelSize:6,yLabelOffset:46,fontFamily:'Arial',dataPadding:.08,showTsne:true,tsneFraction:.42,tsnePointSize:2.2,tsnePointOpacity:.8,tsneOutline:true,tsneOutlineWidth:.6,tsneOutlineOpacity:1,tsneDash:'4 3',tsneShowLabels:false,tsneShowAxes:false,tsneShowColorbar:true,tsneZMin:-2.5,tsneZMax:2.5,tsneLowColor:'#2166ac',tsneMidColor:'#d9d9d9',tsneHighColor:'#b2182b',tsneXMin:-12.55,tsneXMax:9.68,tsneYMin:-19.01,tsneYMax:19.38,tsneUnitRatio:1.2,colors:{E1:'#4E79A7',E2:'#F28E2B',E3:'#59A14F',E4:'#2AA6B8',E5:'#B07AA1'},order:features.map(f=>f.key),visible:Object.fromEntries(features.map(f=>[f.key,true])),labels:Object.fromEntries(features.map(f=>[f.key,{name:f.name,unit:f.unit,min:'',max:''}])),exportWidthIn:7.2,exportDpi:900,exportBackground:'white'};
defaults.pairLayout='stacked-box-first';
let state=structuredClone(defaults),raw=[],pairs=[],omnibus=[],tsne=[],zById=new Map(),regions={};
const $=id=>document.getElementById(id),svg=$('comparisonSvg');
const el=(tag,attrs={},text='')=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!=='')n.textContent=text;return n};
const quantile=(a,q)=>{const s=[...a].sort((x,y)=>x-y),p=(s.length-1)*q,b=Math.floor(p),r=p-b;return s[b+1]===undefined?s[b]:s[b]+r*(s[b+1]-s[b])};
const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0)/4294967295};
function parseCsv(text){const lines=text.trim().split(/\r?\n/),clean=v=>v.replace(/^"|"$/g,'').replaceAll('""','"'),keys=lines.shift().split(',').map(clean);return lines.map(line=>Object.fromEntries(line.split(',').map((v,i)=>[keys[i],clean(v)])))}
function hull(points){points=[...new Map(points.map(p=>[p.join(','),p])).values()].sort((a,b)=>a[0]-b[0]||a[1]-b[1]);if(points.length<3)return points;const cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]),half=[];for(const p of points){while(half.length>1&&cross(half.at(-2),half.at(-1),p)<=0)half.pop();half.push(p)}const lower=half.slice();half.length=0;for(const p of points.toReversed()){while(half.length>1&&cross(half.at(-2),half.at(-1),p)<=0)half.pop();half.push(p)}return lower.slice(0,-1).concat(half.slice(0,-1))}
function chaikin(poly,n=3){for(let k=0;k<n;k++){const out=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];out.push([.75*a[0]+.25*b[0],.75*a[1]+.25*b[1]],[.25*a[0]+.75*b[0],.25*a[1]+.75*b[1]])}poly=out}return poly}
function makeRegion(points){const mx=quantile(points.map(p=>p[0]),.5),my=quantile(points.map(p=>p[1]),.5),sx=quantile(points.map(p=>Math.abs(p[0]-mx)),.5)*1.4826||1,sy=quantile(points.map(p=>Math.abs(p[1]-my)),.5)*1.4826||1,scored=points.map(p=>({p,d:Math.hypot((p[0]-mx)/sx,(p[1]-my)/sy)})),cut=quantile(scored.map(x=>x.d),.95),poly=hull(scored.filter(x=>x.d<=cut).map(x=>x.p));return{poly:chaikin(poly.map(p=>[mx+(p[0]-mx)*1.03,my+(p[1]-my)*1.03])),center:[mx,my]}}
const rgb=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)],mix=(a,b,t)=>{const A=rgb(a),B=rgb(b);return`rgb(${A.map((v,i)=>Math.round(v+(B[i]-v)*t)).join(',')})`};
function zColor(v){const lo=state.tsneZMin,hi=state.tsneZMax,mid=(lo+hi)/2;if(!Number.isFinite(v))return'#d9d9d9';return v<=mid?mix(state.tsneLowColor,state.tsneMidColor,Math.max(0,Math.min(1,(v-lo)/(mid-lo||1)))):mix(state.tsneMidColor,state.tsneHighColor,Math.max(0,Math.min(1,(v-mid)/(hi-mid||1))))}
const selected=()=>state.order.filter(k=>state.visible[k]);
function pText(v){if(state.pNotation==='decimal')return v<.0001?v.toFixed(6).replace(/0+$/,''):v.toFixed(4).replace(/0+$/,'').replace(/\.$/,'');return v.toExponential(1).replace('e-','e−').replace('e+','e+')}
function numberText(v){const a=Math.abs(v);return(a&&a<.01)||a>=1e4?v.toExponential(1).replace('e-','e−'):Number(v.toPrecision(4)).toString()}
function niceTicks(min,max,n){const span=max-min||1,rawStep=span/Math.max(1,n-1),mag=10**Math.floor(Math.log10(Math.abs(rawStep))),norm=rawStep/mag,step=(norm<1.5?1:norm<3?2:norm<7?5:10)*mag,out=[];for(let v=Math.ceil(min/step)*step;v<=max+step*1e-8;v+=step)out.push(Math.abs(v)<step*1e-8?0:v);return out}
function packComparisons(list){const lanes=[];return [...list].sort((a,b)=>(groups.indexOf(a.Group_2)-groups.indexOf(a.Group_1))-(groups.indexOf(b.Group_2)-groups.indexOf(b.Group_1))).map(r=>{const a=groups.indexOf(r.Group_1),b=groups.indexOf(r.Group_2);let lane=0;while((lanes[lane]||[]).some(([x,y])=>a<=y&&b>=x))lane++;(lanes[lane]??=[]).push([a,b]);return{...r,lane}})}
function annotationHeight(featureKey){const valid=state.showP?pairs.filter(p=>p.Feature===featureKey&&+p[state.pSource]<state.pCutoff):[],packed=packComparisons(valid),lanes=packed.length?Math.max(...packed.map(p=>p.lane))+1:0;return(lanes?lanes*state.pRowGap+state.pFontSize+6:0)+(state.showOmnibus?state.pRowGap:0)}
function sharedAnnotationHeight(){const keys=selected();return keys.length?Math.max(...keys.map(annotationHeight)):0}
function yRange(key,values){const cfg=state.labels[key],lo=cfg.min===''?Math.min(...values):+cfg.min,hi=cfg.max===''?Math.max(...values):+cfg.max,span=hi-lo||Math.abs(lo)||1,pad=state.dataPadding*span;return[cfg.min===''?lo-pad:lo,cfg.max===''?hi+pad:hi]}
function addTsne(g,feature,x0,y0,x1,y1){const barH=state.tsneShowColorbar?12:0,pad=state.tsneShowAxes?15:3,aw=x1-x0-pad*2,ah=y1-y0-pad*2-barH,dx=state.tsneXMax-state.tsneXMin,dy=state.tsneYMax-state.tsneYMin,scale=Math.min(aw/dx,ah/(dy/state.tsneUnitRatio)),pw=dx*scale,ph=dy*scale/state.tsneUnitRatio,l=x0+(x1-x0-pw)/2,t=y0+(y1-y0-barH-ph)/2,X=v=>l+(v-state.tsneXMin)*scale,Y=v=>t+ph-(v-state.tsneYMin)*scale/state.tsneUnitRatio;
 if(state.tsneShowAxes){g.append(el('line',{x1:l,y1:t+ph,x2:l+pw,y2:t+ph,stroke:'#111','stroke-width':state.axisLineWidth}));g.append(el('line',{x1:l,y1:t,x2:l,y2:t+ph,stroke:'#111','stroke-width':state.axisLineWidth}));g.append(el('text',{x:l+pw/2,y:t+ph+12,'text-anchor':'middle','font-size':state.axisFontSize},'t-SNE 1'));g.append(el('text',{x:l-11,y:t+ph/2,'text-anchor':'middle','font-size':state.axisFontSize,transform:`rotate(-90 ${l-11} ${t+ph/2})`},'t-SNE 2'))}
 for(const r of tsne){const z=+(zById.get(r.MSN_unique_ID)?.[feature.key]);const c=el('circle',{cx:X(r.x),cy:Y(r.y),r:state.tsnePointSize/2,fill:zColor(z),'fill-opacity':state.tsnePointOpacity});c.append(el('title',{},`${r.MSN_unique_ID}\n${state.labels[feature.key].name} Z-score: ${numberText(z)}`));g.append(c)}
 if(state.tsneOutline)for(const name of groups){const region=regions[name];if(!region?.poly.length)continue;g.append(el('path',{d:region.poly.map((p,i)=>`${i?'L':'M'}${X(p[0])},${Y(p[1])}`).join(' ')+' Z',fill:'none',stroke:state.colors[name],'stroke-width':state.tsneOutlineWidth,'stroke-opacity':state.tsneOutlineOpacity,'stroke-dasharray':state.tsneDash,'vector-effect':'non-scaling-stroke'}));if(state.tsneShowLabels)g.append(el('text',{x:X(region.center[0]),y:Y(region.center[1]),'text-anchor':'middle','dominant-baseline':'middle','font-size':state.axisFontSize,fill:state.colors[name]},name))}
 if(state.tsneShowColorbar){const id=`grad-${feature.key.replace(/[^a-z0-9]/gi,'')}`,defs=el('defs'),grad=el('linearGradient',{id,x1:'0%',x2:'100%'});grad.append(el('stop',{offset:'0%','stop-color':state.tsneLowColor}),el('stop',{offset:'50%','stop-color':state.tsneMidColor}),el('stop',{offset:'100%','stop-color':state.tsneHighColor}));defs.append(grad);g.append(defs);const bw=Math.min(80,pw*.62),bx=l+(pw-bw)/2,by=y1-8;g.append(el('rect',{x:bx,y:by,width:bw,height:3,fill:`url(#${id})`}));g.append(el('text',{x:bx-3,y:by+3,'text-anchor':'end','font-size':state.axisFontSize-1},numberText(state.tsneZMin)));g.append(el('text',{x:bx+bw+3,y:by+3,'text-anchor':'start','font-size':state.axisFontSize-1},numberText(state.tsneZMax)))}
}
function panel(feature,ox,oy){const W=state.panelWidth,H=state.panelHeight,stacked=state.showTsne&&state.pairLayout.startsWith('stacked'),side=state.showTsne&&!stacked,tsneFirst=state.showTsne&&state.pairLayout.endsWith('tsne-first'),reserve=side?Math.max(130,W*state.tsneFraction):0,tsneH=stacked?Math.max(130,H*state.tsneFraction):0,m={l:54,b:34,t:10},validPairs=state.showP?pairs.filter(p=>p.Feature===feature.key&&+p[state.pSource]<state.pCutoff):[],packed=packComparisons(validPairs),lanes=packed.length?Math.max(...packed.map(p=>p.lane))+1:0,omni=omnibus.find(o=>o.Feature===feature.key),panelAnnotation=(lanes?lanes*state.pRowGap+state.pFontSize+6:0)+(state.showOmnibus?state.pRowGap:0),annotation=state.uniformYAxisHeight?sharedAnnotationHeight():panelAnnotation,titleSpace=state.showPanelTitles?state.panelTitleSize+8:0,titleBase=oy+m.t+titleSpace,annotationBase=stacked&&tsneFirst?titleBase+tsneH+state.pairGap:titleBase,availableTop=annotationBase+annotation,bottom=stacked&&!tsneFirst?oy+H-tsneH-state.pairGap-20:oy+H-m.b,left=side&&tsneFirst?ox+reserve+state.pairGap+m.l:ox+m.l,right=side&&!tsneFirst?ox+W-reserve-state.pairGap-12:ox+W-12,top=state.statsAspectRatio>0?Math.max(availableTop,bottom-(right-left)*state.statsAspectRatio):availableTop,all=raw.map(r=>+r[feature.key]).filter(Number.isFinite),[ymin,ymax]=yRange(feature.key,all),Y=v=>bottom-(v-ymin)/(ymax-ymin)*(bottom-top),X=i=>left+(i+.5)*(right-left)/5,g=el('g',{'data-feature':feature.key});g.append(el('rect',{x:ox,y:oy,width:W,height:H,fill:state.canvasColor}));
 if(state.showPanelTitles)g.append(el('text',{x:ox+W/2,y:oy+m.t+state.panelTitleSize,'text-anchor':'middle','font-size':state.panelTitleSize,'font-weight':600},state.labels[feature.key].name));
 if(state.showAxes){g.append(el('line',{x1:left,y1:top,x2:left,y2:bottom,stroke:'#111','stroke-width':state.axisLineWidth,'vector-effect':'non-scaling-stroke'}));g.append(el('line',{x1:left,y1:bottom,x2:right,y2:bottom,stroke:'#111','stroke-width':state.axisLineWidth,'vector-effect':'non-scaling-stroke'}))}
 for(const t of niceTicks(ymin,ymax,state.tickCount)){if(state.showTicks)g.append(el('line',{x1:left-state.tickLength,y1:Y(t),x2:left,y2:Y(t),stroke:'#111','stroke-width':state.axisLineWidth,'vector-effect':'non-scaling-stroke'}));if(state.showTickLabels)g.append(el('text',{x:left-state.tickLength-3,y:Y(t),'text-anchor':'end','dominant-baseline':'middle','font-size':state.axisFontSize},numberText(t)))}
 groups.forEach((name,i)=>{if(state.showXLabels)g.append(el('text',{x:X(i),y:bottom+state.axisFontSize+8,'text-anchor':'middle','font-size':state.axisFontSize},name));const rows=raw.filter(r=>r.E_type===name),vals=rows.map(r=>+r[feature.key]).filter(Number.isFinite);if(state.showPoints)for(const r of rows){const v=+r[feature.key];if(!Number.isFinite(v))continue;const c=el('circle',{cx:X(i)+(hash(r.MSN_unique_ID+feature.key)-.5)*state.jitterWidth*(right-left)/5,cy:Y(v),r:state.pointSize/2,fill:state.colors[name],'fill-opacity':state.pointOpacity});c.append(el('title',{},`${r.MSN_unique_ID}\n${name} · ${state.labels[feature.key].name}: ${v}`));g.append(c)}if(state.showBoxes&&vals.length){const q1=quantile(vals,.25),med=quantile(vals,.5),q3=quantile(vals,.75),iqr=q3-q1,lo=Math.max(Math.min(...vals),q1-1.5*iqr),hi=Math.min(Math.max(...vals),q3+1.5*iqr),notch=Math.min(iqr/2,1.57*iqr/Math.sqrt(vals.length)),pw=(right-left)/5,w=pw*state.boxWidth/2,nw=w*.42,cx=X(i),cap=pw*state.whiskerWidth/2;g.append(el('line',{x1:cx,y1:Y(lo),x2:cx,y2:Y(hi),stroke:'#111','stroke-width':state.boxLineWidth}));for(const v of[lo,hi])g.append(el('line',{x1:cx-cap,y1:Y(v),x2:cx+cap,y2:Y(v),stroke:'#111','stroke-width':state.boxLineWidth}));const d=`M${cx-w},${Y(q3)} L${cx-w},${Y(med+notch)} L${cx-nw},${Y(med)} L${cx-w},${Y(med-notch)} L${cx-w},${Y(q1)} L${cx+w},${Y(q1)} L${cx+w},${Y(med-notch)} L${cx+nw},${Y(med)} L${cx+w},${Y(med+notch)} L${cx+w},${Y(q3)} Z`;g.append(el('path',{d,fill:state.colors[name],'fill-opacity':state.boxFillOpacity,stroke:'#111','stroke-width':state.boxLineWidth}));g.append(el('line',{x1:cx-nw,y1:Y(med),x2:cx+nw,y2:Y(med),stroke:'#111','stroke-width':state.medianLineWidth}))}});
 if(state.showYLabels){const cfg=state.labels[feature.key],label=cfg.unit&&cfg.unit!=='index'&&cfg.unit!=='CV'?`${cfg.name} (${cfg.unit})`:cfg.name,labelX=left-state.yLabelOffset;g.append(el('text',{x:labelX,y:(top+bottom)/2,'text-anchor':'middle','font-size':state.yLabelSize,transform:`rotate(-90 ${labelX} ${(top+bottom)/2})`},label))}
 packed.forEach(p=>{const y=top-6-p.lane*state.pRowGap,a=X(groups.indexOf(p.Group_1)),b=X(groups.indexOf(p.Group_2));g.append(el('line',{x1:a,y1:y+state.pLabelGap,x2:b,y2:y+state.pLabelGap,stroke:'#111','stroke-width':state.pLineWidth}));g.append(el('text',{x:(a+b)/2,y:y,'text-anchor':'middle','font-size':state.pFontSize},pText(+p[state.pSource])))});
 if(state.showOmnibus&&omni){const value=+omni.P_adj_BH_across_18_features,omnibusY=top-6-lanes*state.pRowGap;g.append(el('text',{x:right,y:omnibusY,'text-anchor':'end','font-size':state.pFontSize},`K–W ${pText(value)}`))}if(state.showTsne){if(stacked&&tsneFirst)addTsne(g,feature,ox+12,titleBase,ox+W-5,titleBase+tsneH);else if(stacked)addTsne(g,feature,ox+12,bottom+state.pairGap+14,ox+W-5,oy+H-5);else if(tsneFirst)addTsne(g,feature,ox+5,titleBase,left-state.pairGap,oy+H-5);else addTsne(g,feature,right+state.pairGap,titleBase,ox+W-5,bottom)}return g}
function render(){if(!raw.length)return;sync();svg.replaceChildren();const list=selected(),cols=Math.min(state.columns,Math.max(1,list.length)),rowsN=Math.ceil(list.length/cols),w=cols*state.panelWidth+(cols-1)*state.panelGapX,h=rowsN*state.panelHeight+(rowsN-1)*state.panelGapY;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.style.background=state.canvasColor;svg.style.fontFamily=state.fontFamily;list.forEach((key,i)=>svg.append(panel(features.find(f=>f.key===key),(i%cols)*(state.panelWidth+state.panelGapX),Math.floor(i/cols)*(state.panelHeight+state.panelGapY))));const pxW=Math.round(state.exportWidthIn*state.exportDpi),pxH=Math.round(pxW*h/w);$('exportPixels').value=`${pxW.toLocaleString()} × ${pxH.toLocaleString()} px`;$('comparisonStatus').textContent=`${list.length}/18 features · 450 cells · adjusted pairwise values shown without recomputation · export ${pxW.toLocaleString()} × ${pxH.toLocaleString()} px`}
function featureControls(){$('comparisonFeatureControls').innerHTML=state.order.map((key,i)=>{const c=state.labels[key];return`<div class="comparison-feature-row"><input aria-label="Show ${c.name}" data-visible="${key}" type="checkbox" ${state.visible[key]?'checked':''}><input aria-label="Feature name" data-name="${key}" value="${c.name}"><input aria-label="Unit" data-unit="${key}" value="${c.unit}"><input aria-label="Y minimum" data-min="${key}" type="number" step="any" placeholder="auto" value="${c.min}"><input aria-label="Y maximum" data-max="${key}" type="number" step="any" placeholder="auto" value="${c.max}"><button data-up="${key}" ${i?'':'disabled'}>↑</button><button data-down="${key}" ${i<state.order.length-1?'':'disabled'}>↓</button></div>`}).join('');document.querySelectorAll('[data-visible]').forEach(n=>n.onchange=()=>{if(!n.checked&&selected().length<=1){n.checked=true;return}state.visible[n.dataset.visible]=n.checked;render()});for(const prop of['name','unit','min','max'])document.querySelectorAll(`[data-${prop}]`).forEach(n=>n.oninput=()=>{state.labels[n.dataset[prop]][prop]=n.value;render()});document.querySelectorAll('[data-up]').forEach(n=>n.onclick=()=>move(n.dataset.up,-1));document.querySelectorAll('[data-down]').forEach(n=>n.onclick=()=>move(n.dataset.down,1))}
function move(key,d){const i=state.order.indexOf(key),j=i+d;if(j<0||j>=state.order.length)return;[state.order[i],state.order[j]]=[state.order[j],state.order[i]];featureControls();render()}
function controls(){$('comparisonColorControls').innerHTML=groups.map(g=>`<label>${g}<input data-color="${g}" type="color" value="${state.colors[g]}"></label>`).join('');featureControls();document.querySelectorAll('[data-color]').forEach(n=>n.oninput=()=>{state.colors[n.dataset.color]=n.value;render()});$('selectAll9').onclick=()=>{features.forEach(f=>state.visible[f.key]=true);featureControls();render()};$('selectCore6').onclick=()=>{features.forEach(f=>state.visible[f.key]=core6.includes(f.key));featureControls();render()};const specs={pairLayout:'str',pairGap:'num',uniformYAxisHeight:'bool',statsAspectRatio:'num',columns:'int',panelWidth:'num',panelHeight:'num',panelGapX:'num',panelGapY:'num',canvasColor:'str',showPanelTitles:'bool',panelTitleSize:'num',showPoints:'bool',pointSize:'num',pointOpacity:'num',jitterWidth:'num',showBoxes:'bool',boxWidth:'num',boxLineWidth:'num',boxFillOpacity:'num',whiskerWidth:'num',medianLineWidth:'num',showP:'bool',pSource:'str',pCutoff:'num',pFontSize:'num',pLineWidth:'num',pRowGap:'num',pLabelGap:'num',pNotation:'str',showOmnibus:'bool',showTsne:'bool',tsneFraction:'num',tsnePointSize:'num',tsnePointOpacity:'num',tsneOutline:'bool',tsneOutlineWidth:'num',tsneOutlineOpacity:'num',tsneDash:'str',tsneShowLabels:'bool',tsneShowAxes:'bool',tsneShowColorbar:'bool',tsneZMin:'num',tsneZMax:'num',tsneLowColor:'str',tsneMidColor:'str',tsneHighColor:'str',tsneXMin:'num',tsneXMax:'num',tsneYMin:'num',tsneYMax:'num',tsneUnitRatio:'num',showAxes:'bool',showTicks:'bool',showTickLabels:'bool',showXLabels:'bool',showYLabels:'bool',axisLineWidth:'num',tickLength:'num',tickCount:'int',axisFontSize:'num',yLabelSize:'num',yLabelOffset:'num',fontFamily:'str',dataPadding:'num',exportWidthIn:'num',exportDpi:'int',exportBackground:'str'};for(const[id,type]of Object.entries(specs)){const n=$(id);n.addEventListener(n.type==='range'?'input':'change',()=>{state[id]=type==='bool'?n.checked:type==='num'?+n.value:type==='int'?parseInt(n.value):n.value;render()})}$('resetAll').onclick=()=>{state=structuredClone(defaults);featureControls();sync();render()};$('exportSvg').onclick=exportSvg;$('exportPng').onclick=()=>runExport('PNG',exportPng);$('exportTif').onclick=()=>runExport('TIF',exportTif);$('exportPdf').onclick=()=>runExport('PDF',exportPdf);$('exportStats').onclick=exportStats;$('exportLayout').onclick=exportLayout;$('importLayout').onchange=importLayout}
function sync(){for(const[k,v]of Object.entries(state)){const n=$(k);if(!n||typeof v==='object')continue;if(n.type==='checkbox')n.checked=v;else n.value=v;const o=$(k+'Value');if(o)o.value=typeof v==='number'?(Number.isInteger(v)?v:v.toFixed(2)):v}document.querySelectorAll('[data-color]').forEach(n=>n.value=state.colors[n.dataset.color])}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function serialized(background=null){const copy=svg.cloneNode(true);copy.setAttribute('xmlns',NS);copy.setAttribute('width',svg.viewBox.baseVal.width);copy.setAttribute('height',svg.viewBox.baseVal.height);if(background)copy.insertBefore(el('rect',{x:0,y:0,width:'100%',height:'100%',fill:background}),copy.firstChild);return new XMLSerializer().serializeToString(copy)}
function exportSvg(){download(new Blob([serialized(state.exportBackground==='transparent'?null:'#fff')],{type:'image/svg+xml'}),'Mouse_E1-E5_final_features_comparison.svg')}
async function runExport(label,fn){const old=$('comparisonStatus').textContent;try{$('comparisonStatus').textContent=`Rendering ${label} from the current preview…`;await fn();$('comparisonStatus').textContent=`${label} export complete`}catch(e){$('comparisonStatus').textContent=`${label} export failed: ${e.message}`}setTimeout(()=>{if($('comparisonStatus').textContent.includes('complete'))$('comparisonStatus').textContent=old},2200)}
async function raster(forceWhite=false){const w=Math.round(state.exportWidthIn*state.exportDpi),h=Math.round(w*svg.viewBox.baseVal.height/svg.viewBox.baseVal.width);if(w*h>8e7)throw Error('requested export exceeds the safe 80-megapixel browser limit');const transparent=state.exportBackground==='transparent'&&!forceWhite,img=new Image(),url=URL.createObjectURL(new Blob([serialized(transparent?null:'#fff')],{type:'image/svg+xml'}));await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:transparent});if(!transparent){x.fillStyle='#fff';x.fillRect(0,0,w,h)}x.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);return c}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function pngDpi(bytes,dpi){const ppm=Math.round(dpi/.0254),data=new Uint8Array(9),v=new DataView(data.buffer);v.setUint32(0,ppm);v.setUint32(4,ppm);data[8]=1;const type=new TextEncoder().encode('pHYs'),chunk=new Uint8Array(21),cv=new DataView(chunk.buffer);cv.setUint32(0,9);chunk.set(type,4);chunk.set(data,8);cv.setUint32(17,crc32(chunk.slice(4,17)));const out=new Uint8Array(bytes.length+21);out.set(bytes.slice(0,33));out.set(chunk,33);out.set(bytes.slice(33),54);return out}
async function exportPng(){const c=await raster(),b=await new Promise(ok=>c.toBlob(ok,'image/png')),png=pngDpi(new Uint8Array(await b.arrayBuffer()),state.exportDpi);download(new Blob([png],{type:'image/png'}),`Mouse_E_comparison_${state.exportDpi}dpi.png`)}
function tiff(c,dpi){const{width:w,height:h}=c,img=c.getContext('2d').getImageData(0,0,w,h).data,n=14,ifd=8,bits=ifd+2+n*12+4,xres=bits+6,yres=xres+8,pixels=yres+8,bytes=new Uint8Array(pixels+w*h*3),v=new DataView(bytes.buffer);bytes[0]=73;bytes[1]=73;v.setUint16(2,42,true);v.setUint32(4,ifd,true);v.setUint16(ifd,n,true);let p=ifd+2;const e=(tag,type,count,value,short=false)=>{v.setUint16(p,tag,true);v.setUint16(p+2,type,true);v.setUint32(p+4,count,true);short?v.setUint16(p+8,value,true):v.setUint32(p+8,value,true);p+=12};e(256,4,1,w);e(257,4,1,h);e(258,3,3,bits);e(259,3,1,1,true);e(262,3,1,2,true);e(273,4,1,pixels);e(274,3,1,1,true);e(277,3,1,3,true);e(278,4,1,h);e(279,4,1,w*h*3);e(282,5,1,xres);e(283,5,1,yres);e(284,3,1,1,true);e(296,3,1,2,true);v.setUint32(p,0,true);[0,2,4].forEach(o=>v.setUint16(bits+o,8,true));v.setUint32(xres,dpi,true);v.setUint32(xres+4,1,true);v.setUint32(yres,dpi,true);v.setUint32(yres+4,1,true);for(let i=0,j=pixels;i<img.length;i+=4){bytes[j++]=img[i];bytes[j++]=img[i+1];bytes[j++]=img[i+2]}return new Blob([bytes],{type:'image/tiff'})}
async function exportTif(){const c=await raster(true);download(tiff(c,state.exportDpi),`Mouse_E_comparison_${state.exportDpi}dpi.tif`)}
function pdf(jpeg,w,h,widthIn){const enc=new TextEncoder(),parts=[],offsets=[0],push=x=>parts.push(typeof x==='string'?enc.encode(x):x),pw=widthIn*72,ph=pw*h/w;push('%PDF-1.4\n');let len=parts.reduce((a,b)=>a+b.length,0);const obj=(id,body)=>{offsets[id]=len;const a=enc.encode(`${id} 0 obj\n${body}\nendobj\n`);parts.push(a);len+=a.length};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');obj(3,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);offsets[4]=len;push(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`);push(jpeg);push('\nendstream\nendobj\n');len=parts.reduce((a,b)=>a+b.length,0);const content=`q\n${pw} 0 0 ${ph} 0 0 cm\n/Im0 Do\nQ`;obj(5,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);const xref=len;push(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(parts,{type:'application/pdf'})}
async function exportPdf(){const c=await raster(true),b=await new Promise(ok=>c.toBlob(ok,'image/jpeg',.98)),jpg=new Uint8Array(await b.arrayBuffer());download(pdf(jpg,c.width,c.height,state.exportWidthIn),`Mouse_E_comparison_${state.exportDpi}dpi.pdf`)}
function csvValue(v){return`"${String(v??'').replaceAll('"','""')}"`}function exportStats(){const keys=selected(),head=['Feature','Display_name','Unit','Test','Group_1','Group_2','N_1','N_2','Statistic','Effect_size','P_raw','P_adjusted','Adjustment'];const lines=[head,...pairs.filter(p=>keys.includes(p.Feature)).map(p=>[p.Feature,p.Display_name,p.Unit,'Two-sided Dunn test',p.Group_1,p.Group_2,p.N_1,p.N_2,p.Dunn_Z,p.Dunn_r,p.P_raw,p[state.pSource],state.pSource])];download(new Blob([lines.map(r=>r.map(csvValue).join(',')).join('\n')],{type:'text/csv'}),'Mouse_E_selected_features_pairwise_statistics.csv')}
function exportLayout(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'Mouse_E_comparison_layout.json')}
function completeLayout(x={}){const base=structuredClone(defaults),incoming=Array.isArray(x.order)?x.order.filter(k=>features.some(f=>f.key===k)):[];return{...base,...x,order:[...incoming,...features.map(f=>f.key).filter(k=>!incoming.includes(k))],colors:{...base.colors,...x.colors},labels:{...base.labels,...x.labels},visible:{...base.visible,...x.visible}}}
async function importLayout(e){const f=e.target.files[0];if(!f)return;try{state=completeLayout(JSON.parse(await f.text()));featureControls();sync();render()}catch{$('comparisonStatus').textContent='The selected layout could not be read.'}e.target.value=''}
console.assert(packComparisons([{Group_1:'E1',Group_2:'E2'},{Group_1:'E3',Group_2:'E4'}]).every(x=>x.lane===0),'Comparison packing self-check failed');
try{const [rawData,pairData,omnibusData,tsneText,zText,savedLayout]=await Promise.all([fetch('data/raw.json').then(r=>r.json()),fetch('data/pairwise.json').then(r=>r.json()),fetch('data/omnibus.json').then(r=>r.json()),fetch('data/tsne_cells.csv').then(r=>r.text()),fetch('data/final18_zscore_long.csv').then(r=>r.text()),fetch('data/comparison_default_layout.json?v=y-title-distance-20260920').then(r=>r.json())]);raw=rawData;pairs=pairData;omnibus=omnibusData;const rawIds=new Set(raw.map(r=>r.MSN_unique_ID));for(const r of parseCsv(zText)){if(!rawIds.has(r.Cell_ID))continue;const row=zById.get(r.Cell_ID)||{};row[r.Feature_full]=+r.Z_score;zById.set(r.Cell_ID,row)}tsne=parseCsv(tsneText).filter(r=>/true/i.test(r.HC_GC_consensus)&&zById.has(r.MSN_unique_ID)).map(r=>({...r,x:+r.tSNE_1,y:+r.tSNE_2,E_type:r.HC_GC_consensus_E}));if(raw.length!==450||zById.size!==450||tsne.length!==450||[...zById.values()].some(r=>features.some(f=>!Number.isFinite(r[f.key]))))throw Error(`Expected 450 matched cells with 18 frozen Z-scores`);Object.assign(defaults,completeLayout(savedLayout));state=structuredClone(defaults);for(const g of groups){if(raw.filter(r=>r.E_type===g).length!==counts[g])throw Error(`Frozen ${g} count changed`);regions[g]=makeRegion(tsne.filter(r=>r.E_type===g).map(r=>[r.x,r.y]))}controls();sync();render()}catch(e){$('comparisonStatus').textContent='Unable to load comparison data: '+e.message}
