const NS='http://www.w3.org/2000/svg';
const classes=['E1','E2','E3','E4','E5'];
const featureDefs=[
 {key:'E_Input.resistance..MOhm.',label:'Rin'},
 {key:'E_Membrane.time.constant..ms.',label:'Tau'},
 {key:'E_Rheobase..pA.',label:'Rheo'},
 {key:'E_Max.number.of.APs',label:'MaxAP'},
 {key:'E_Afterhyperpolarization..mV.',label:'AHP'},
 {key:'E_AP.amplitude.adaptation.index',label:'APad'}
 ,{key:'E_AP.amplitude..mV.',label:'APamp'}
 ,{key:'E_ISI.adaptation.index',label:'ISIad'}
 ,{key:'E_ISI.coefficient.of.variation',label:'ISIcv'}
];
const counts={E1:142,E2:160,E3:45,E4:61,E5:42};
const core6=featureDefs.slice(0,6).map(f=>f.key);
const defaults={colors:{E1:'#4E79A7',E2:'#F28E2B',E3:'#59A14F',E4:'#2AA6B8',E5:'#B07AA1'},overallColor:'#4c78a8',canvasColor:'#ffffff',columns:5,panelWidth:250,panelHeight:200,panelGap:0,rowGap:8,showOverall:false,showTitles:true,showCounts:true,titleSize:7,zMin:-3,zMax:3,radius:58,startAngle:-90,clockwise:true,smoothing:.65,centerX:0,centerY:8,showCells:true,cellWidth:.25,cellOpacity:.08,showMedian:true,medianWidth:.9,medianColorMode:'black',medianFill:.18,showIqr:true,iqrOpacity:.12,showRings:true,showSpokes:true,ringCount:6,gridColor:'#a6a6a6',gridWidth:.35,gridOpacity:.42,outerWidth:.35,labelRadius:1.12,labelSize:6,labelColor:'#222222',labelOrientation:'tangent',fontFamily:'Arial',panelOrder:[...classes],panels:Object.fromEntries(classes.map(c=>[c,{visible:true,title:c}])),featureOrder:featureDefs.map(f=>f.key),featureVisible:Object.fromEntries(featureDefs.map(f=>[f.key,true])),featureLabels:Object.fromEntries(featureDefs.map(f=>[f.key,f.label])),exportWidthIn:6.25,exportDpi:600,exportBackground:'white'};
let state=structuredClone(defaults),rows=[];
const $=id=>document.getElementById(id),svg=$('radarSvg');
const el=(tag,attrs={},text='')=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const quantile=(a,p)=>{const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return s[l]+(s[h]-s[l])*(i-l)};
const unquote=v=>v.replace(/^\uFEFF/,'').replace(/^"|"$/g,'');
const parseCsv=text=>{const[h,...lines]=text.trim().split(/\r?\n/),keys=h.split(',').map(unquote);return lines.map(line=>Object.fromEntries(line.split(',').map((v,i)=>[keys[i],unquote(v)])))};
const activeFeatures=()=>state.featureOrder.filter(k=>state.featureVisible[k]);
const angle=(i,n)=>(state.startAngle+(state.clockwise?1:-1)*i*360/n)*Math.PI/180;
const radial=z=>clamp((z-state.zMin)/(state.zMax-state.zMin),0,1);
console.assert(radial(-3)===0&&radial(0)===.5&&radial(3)===1,'Frozen Z-to-radius mapping self-check failed');
function point(cx,cy,r,i,n){const a=angle(i,n);return[cx+Math.cos(a)*r,cy+Math.sin(a)*r]}
function smoothPath(points,closed=true){if(!points.length)return'';if(state.smoothing<=0)return points.map((p,i)=>(i?'L':'M')+p[0].toFixed(2)+' '+p[1].toFixed(2)).join(' ')+(closed?' Z':'');const n=points.length,t=state.smoothing/6,out=[`M${points[0][0].toFixed(2)} ${points[0][1].toFixed(2)}`];for(let i=0;i<n;i++){const p0=points[(i-1+n)%n],p1=points[i],p2=points[(i+1)%n],p3=points[(i+2)%n],c1=[p1[0]+(p2[0]-p0[0])*t,p1[1]+(p2[1]-p0[1])*t],c2=[p2[0]-(p3[0]-p1[0])*t,p2[1]-(p3[1]-p1[1])*t];out.push(`C${c1[0].toFixed(2)} ${c1[1].toFixed(2)} ${c2[0].toFixed(2)} ${c2[1].toFixed(2)} ${p2[0].toFixed(2)} ${p2[1].toFixed(2)}`)}return out.join(' ')+(closed?' Z':'')}
function valuesPath(values,cx,cy){return smoothPath(values.map((z,i)=>point(cx,cy,state.radius*radial(z),i,values.length)))}
function labelRotation(i,n){let d=angle(i,n)*180/Math.PI+90;if(state.labelOrientation==='horizontal')return 0;if(state.labelOrientation==='radial')d-=90;d=((d%360)+360)%360;if(d>90&&d<270)d+=180;return d}
function buildControls(){
 $('colorControls').innerHTML=classes.map(c=>`<label>${c}<input data-color="${c}" type="color" value="${state.colors[c]}"></label>`).join('');
 renderPanelControls();renderFeatureControls();
 $('useCore6').onclick=()=>{for(const f of featureDefs)state.featureVisible[f.key]=core6.includes(f.key);renderFeatureControls();render()};$('useAll9').onclick=()=>{for(const f of featureDefs)state.featureVisible[f.key]=true;renderFeatureControls();render()};
 const specs={columns:'int',panelWidth:'num',panelHeight:'num',panelGap:'num',rowGap:'num',showOverall:'bool',showTitles:'bool',showCounts:'bool',titleSize:'num',canvasColor:'str',zMin:'num',zMax:'num',radius:'num',startAngle:'num',clockwise:'bool',smoothing:'num',centerX:'num',centerY:'num',showCells:'bool',cellWidth:'num',cellOpacity:'num',showMedian:'bool',medianWidth:'num',medianColorMode:'str',medianFill:'num',showIqr:'bool',iqrOpacity:'num',showRings:'bool',showSpokes:'bool',ringCount:'int',gridColor:'str',gridWidth:'num',gridOpacity:'num',outerWidth:'num',labelRadius:'num',labelSize:'num',labelColor:'str',labelOrientation:'str',fontFamily:'str',overallColor:'str',exportWidthIn:'num',exportDpi:'int',exportBackground:'str'};
 for(const[id,type]of Object.entries(specs)){const n=$(id);if(!n)continue;n.addEventListener(n.type==='range'?'input':'change',()=>{const value=type==='bool'?n.checked:type==='num'?+n.value:type==='int'?parseInt(n.value):n.value;if((id==='zMin'&&value>=state.zMax)||(id==='zMax'&&value<=state.zMin)){status('Z maximum must exceed Z minimum.');return}state[id]=value;render()})}
 document.querySelectorAll('[data-color]').forEach(n=>n.oninput=()=>{state.colors[n.dataset.color]=n.value;render()});
 $('resetAll').onclick=()=>{state=structuredClone(defaults);sync();renderPanelControls();renderFeatureControls();render()};
 $('exportSvg').onclick=exportSvg;$('exportPng').onclick=()=>runExport('PNG',exportPng);$('exportTif').onclick=()=>runExport('TIF',exportTif);$('exportPdf').onclick=()=>runExport('PDF',exportPdf);$('exportCsv').onclick=exportCsv;$('exportLayout').onclick=exportLayout;$('importLayout').onchange=importLayout;
}
function renderPanelControls(){$('panelControls').innerHTML=state.panelOrder.map((c,i)=>`<div class="panel-row"><label class="check"><input data-panel-visible="${c}" type="checkbox" ${state.panels[c].visible?'checked':''}>${c}</label><input data-panel-title="${c}" value="${state.panels[c].title}"><span><button data-panel-up="${c}" ${i?'':'disabled'}>↑</button><button data-panel-down="${c}" ${i<state.panelOrder.length-1?'':'disabled'}>↓</button></span></div>`).join('');document.querySelectorAll('[data-panel-visible]').forEach(n=>n.onchange=()=>{state.panels[n.dataset.panelVisible].visible=n.checked;render()});document.querySelectorAll('[data-panel-title]').forEach(n=>n.oninput=()=>{state.panels[n.dataset.panelTitle].title=n.value;render()});document.querySelectorAll('[data-panel-up]').forEach(n=>n.onclick=()=>move(state.panelOrder,n.dataset.panelUp,-1,renderPanelControls));document.querySelectorAll('[data-panel-down]').forEach(n=>n.onclick=()=>move(state.panelOrder,n.dataset.panelDown,1,renderPanelControls))}
function renderFeatureControls(){$('featureControls').innerHTML=state.featureOrder.map((key,i)=>`<div class="feature-row"><input aria-label="Use ${state.featureLabels[key]}" data-feature-visible="${key}" type="checkbox" ${state.featureVisible[key]?'checked':''}><input data-feature-label="${key}" value="${state.featureLabels[key]}"><button data-feature-up="${key}" ${i?'':'disabled'}>↑</button><button data-feature-down="${key}" ${i<state.featureOrder.length-1?'':'disabled'}>↓</button></div>`).join('');document.querySelectorAll('[data-feature-visible]').forEach(n=>n.onchange=()=>{const selected=activeFeatures().length;if(!n.checked&&selected<=3){n.checked=true;status('Keep at least three features for a radar plot.');return}state.featureVisible[n.dataset.featureVisible]=n.checked;render()});document.querySelectorAll('[data-feature-label]').forEach(n=>n.oninput=()=>{state.featureLabels[n.dataset.featureLabel]=n.value;render()});document.querySelectorAll('[data-feature-up]').forEach(n=>n.onclick=()=>move(state.featureOrder,n.dataset.featureUp,-1,renderFeatureControls));document.querySelectorAll('[data-feature-down]').forEach(n=>n.onclick=()=>move(state.featureOrder,n.dataset.featureDown,1,renderFeatureControls))}
function move(a,key,d,refresh){const i=a.indexOf(key),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];refresh();render()}
function sync(){for(const[k,v]of Object.entries(state)){const n=$(k);if(!n||typeof v==='object')continue;if(n.type==='checkbox')n.checked=v;else n.value=v;const o=$(k+'Value');if(o)o.value=typeof v==='number'?(Number.isInteger(v)?v:v.toFixed(2)):v}document.querySelectorAll('[data-color]').forEach(n=>n.value=state.colors[n.dataset.color])}
function stats(subset,features){return features.map(key=>{const a=subset.map(r=>r[key]);return[quantile(a,.25),quantile(a,.5),quantile(a,.75)]})}
function render(){if(!rows.length)return;const features=activeFeatures();sync();svg.replaceChildren();const panels=[...(state.showOverall?[{id:'All',title:'Overall',color:state.overallColor,rows}]:[]),...state.panelOrder.filter(c=>state.panels[c].visible).map(c=>({id:c,title:state.panels[c].title,color:state.colors[c],rows:rows.filter(r=>r.E_class===c)}))],cols=Math.min(state.columns,Math.max(1,panels.length)),nr=Math.ceil(panels.length/cols),w=cols*state.panelWidth+(cols-1)*state.panelGap,h=nr*state.panelHeight+(nr-1)*state.rowGap;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.style.background=state.canvasColor;svg.style.fontFamily=state.fontFamily;
 panels.forEach((p,i)=>{const ox=(i%cols)*(state.panelWidth+state.panelGap),oy=Math.floor(i/cols)*(state.panelHeight+state.rowGap),cx=ox+state.panelWidth/2+state.centerX,cy=oy+state.panelHeight/2+state.centerY,g=el('g',{'data-panel':p.id});svg.append(g);g.append(el('rect',{x:ox,y:oy,width:state.panelWidth,height:state.panelHeight,fill:state.canvasColor}));
  if(state.showRings)for(let k=1;k<=state.ringCount;k++)g.append(el('circle',{cx,cy,r:state.radius*k/state.ringCount,fill:'none',stroke:state.gridColor,'stroke-width':k===state.ringCount?state.outerWidth:state.gridWidth,'stroke-opacity':state.gridOpacity,'vector-effect':'non-scaling-stroke'}));
  if(state.showSpokes)features.forEach((_,j)=>{const q=point(cx,cy,state.radius,j,features.length);g.append(el('line',{x1:cx,y1:cy,x2:q[0],y2:q[1],stroke:state.gridColor,'stroke-width':state.gridWidth,'stroke-opacity':state.gridOpacity,'vector-effect':'non-scaling-stroke'}))});
  if(state.showCells)for(const r of p.rows){const path=el('path',{d:valuesPath(features.map(k=>r[k]),cx,cy),fill:'none',stroke:p.color,'stroke-width':state.cellWidth,'stroke-opacity':state.cellOpacity,'vector-effect':'non-scaling-stroke'});path.append(el('title',{},`${r.Cell_ID} · ${r.E_class}`));g.append(path)}
  const s=stats(p.rows,features),q25=s.map(x=>x[0]),med=s.map(x=>x[1]),q75=s.map(x=>x[2]);if(state.showIqr){const outer=q75.map((z,j)=>point(cx,cy,state.radius*radial(z),j,features.length)),inner=q25.map((z,j)=>point(cx,cy,state.radius*radial(z),j,features.length)).reverse();g.append(el('path',{d:smoothPath(outer)+smoothPath(inner),fill:p.color,'fill-opacity':state.iqrOpacity,'fill-rule':'evenodd',stroke:'none'}))}if(state.showMedian)g.append(el('path',{d:valuesPath(med,cx,cy),fill:p.color,'fill-opacity':state.medianFill,stroke:state.medianColorMode==='black'?'#111111':p.color,'stroke-width':state.medianWidth,'vector-effect':'non-scaling-stroke'}));
  features.forEach((key,j)=>{const q=point(cx,cy,state.radius*state.labelRadius,j,features.length),rot=labelRotation(j,features.length);g.append(el('text',{x:q[0],y:q[1],'text-anchor':'middle','dominant-baseline':'middle','font-size':state.labelSize,fill:state.labelColor,transform:`rotate(${rot} ${q[0]} ${q[1]})`},state.featureLabels[key]))});if(state.showTitles){const title=state.showCounts?`${p.title} (n=${p.rows.length})`:p.title;g.append(el('text',{x:ox+state.panelWidth/2,y:oy+state.titleSize+3,'text-anchor':'middle','font-size':state.titleSize,fill:p.color},title))}
 });const pxW=Math.round(state.exportWidthIn*state.exportDpi),pxH=Math.round(pxW*h/w);$('exportPixels').value=`${pxW.toLocaleString()} × ${pxH.toLocaleString()} px`;status(`450 cells · ${features.length}/9 features selected · E1 142 · E2 160 · E3 45 · E4 61 · E5 42 · shared display Z range ${state.zMin} to ${state.zMax}`)}
function status(s){$('radarStatus').textContent=s}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function serialized(background=null){const copy=svg.cloneNode(true);copy.setAttribute('xmlns',NS);copy.setAttribute('width',svg.viewBox.baseVal.width);copy.setAttribute('height',svg.viewBox.baseVal.height);if(background){const r=el('rect',{x:0,y:0,width:'100%',height:'100%',fill:background});copy.insertBefore(r,copy.firstChild)}return new XMLSerializer().serializeToString(copy)}
function exportSvg(){download(new Blob([serialized(state.exportBackground==='transparent'?null:'#ffffff')],{type:'image/svg+xml'}),'E1-E5_selectable_radar.svg')}
async function runExport(label,fn){const old=$('radarStatus').textContent;try{status(`Rendering ${label} at ${state.exportDpi} DPI…`);await fn();status(`${label} export complete`)}catch(e){status(`${label} export failed: ${e.message}`)}setTimeout(()=>{if($('radarStatus').textContent.includes('complete'))status(old)},2200)}
async function rasterCanvas(forceWhite=false){const width=Math.round(state.exportWidthIn*state.exportDpi),height=Math.round(width*svg.viewBox.baseVal.height/svg.viewBox.baseVal.width);if(width*height>8e7)throw Error('requested image exceeds the safe 80-megapixel limit');const transparent=state.exportBackground==='transparent'&&!forceWhite,img=new Image(),url=URL.createObjectURL(new Blob([serialized(transparent?null:'#ffffff')],{type:'image/svg+xml'}));await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});const c=document.createElement('canvas');c.width=width;c.height=height;const x=c.getContext('2d',{alpha:transparent});if(!transparent){x.fillStyle='#fff';x.fillRect(0,0,width,height)}x.drawImage(img,0,0,width,height);URL.revokeObjectURL(url);return c}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function pngWithDpi(bytes,dpi){const ppm=Math.round(dpi/.0254),data=new Uint8Array(9),v=new DataView(data.buffer);v.setUint32(0,ppm);v.setUint32(4,ppm);data[8]=1;const type=new TextEncoder().encode('pHYs'),chunk=new Uint8Array(21),cv=new DataView(chunk.buffer);cv.setUint32(0,9);chunk.set(type,4);chunk.set(data,8);cv.setUint32(17,crc32(chunk.slice(4,17)));const out=new Uint8Array(bytes.length+21);out.set(bytes.slice(0,33));out.set(chunk,33);out.set(bytes.slice(33),54);return out}
async function exportPng(){const c=await rasterCanvas(),blob=await new Promise(ok=>c.toBlob(ok,'image/png')),png=pngWithDpi(new Uint8Array(await blob.arrayBuffer()),state.exportDpi);download(new Blob([png],{type:'image/png'}),`E1-E5_selectable_radar_${state.exportDpi}dpi.png`)}
function tiffBlob(c,dpi){const{width:w,height:h}=c,img=c.getContext('2d').getImageData(0,0,w,h).data,n=14,ifd=8,bits=ifd+2+n*12+4,xres=bits+6,yres=xres+8,pixels=yres+8,bytes=new Uint8Array(pixels+w*h*3),v=new DataView(bytes.buffer);bytes[0]=73;bytes[1]=73;v.setUint16(2,42,true);v.setUint32(4,ifd,true);v.setUint16(ifd,n,true);let p=ifd+2;const entry=(tag,type,count,value,short=false)=>{v.setUint16(p,tag,true);v.setUint16(p+2,type,true);v.setUint32(p+4,count,true);short?v.setUint16(p+8,value,true):v.setUint32(p+8,value,true);p+=12};entry(256,4,1,w);entry(257,4,1,h);entry(258,3,3,bits);entry(259,3,1,1,true);entry(262,3,1,2,true);entry(273,4,1,pixels);entry(274,3,1,1,true);entry(277,3,1,3,true);entry(278,4,1,h);entry(279,4,1,w*h*3);entry(282,5,1,xres);entry(283,5,1,yres);entry(284,3,1,1,true);entry(296,3,1,2,true);v.setUint32(p,0,true);[0,2,4].forEach(o=>v.setUint16(bits+o,8,true));v.setUint32(xres,dpi,true);v.setUint32(xres+4,1,true);v.setUint32(yres,dpi,true);v.setUint32(yres+4,1,true);for(let i=0,j=pixels;i<img.length;i+=4){bytes[j++]=img[i];bytes[j++]=img[i+1];bytes[j++]=img[i+2]}return new Blob([bytes],{type:'image/tiff'})}
async function exportTif(){const c=await rasterCanvas(true);download(tiffBlob(c,state.exportDpi),`E1-E5_selectable_radar_${state.exportDpi}dpi.tif`)}
function pdfBlob(jpeg,w,h,widthIn){const enc=new TextEncoder(),parts=[],offsets=[0],push=x=>parts.push(typeof x==='string'?enc.encode(x):x),pageW=widthIn*72,pageH=pageW*h/w;push('%PDF-1.4\n');let length=parts.reduce((a,b)=>a+b.length,0);const obj=(id,body)=>{offsets[id]=length;const a=enc.encode(`${id} 0 obj\n${body}\nendobj\n`);parts.push(a);length+=a.length};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,'<< /Type /Pages /Kids [3 0 R] /Count 1 >>');obj(3,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageW} ${pageH}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);offsets[4]=length;push(`4 0 obj\n<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`);push(jpeg);push('\nendstream\nendobj\n');length=parts.reduce((a,b)=>a+b.length,0);const content=`q\n${pageW} 0 0 ${pageH} 0 0 cm\n/Im0 Do\nQ`;obj(5,`<< /Length ${content.length} >>\nstream\n${content}\nendstream`);const xref=length;push(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);return new Blob(parts,{type:'application/pdf'})}
async function exportPdf(){const c=await rasterCanvas(true),blob=await new Promise(ok=>c.toBlob(ok,'image/jpeg',.98)),jpeg=new Uint8Array(await blob.arrayBuffer());download(pdfBlob(jpeg,c.width,c.height,state.exportWidthIn),`E1-E5_selectable_radar_${state.exportDpi}dpi.pdf`)}
function exportCsv(){const head=['Cell_ID','E_class',...featureDefs.map(f=>f.key)];download(new Blob([head.join(',')+'\n'+rows.map(r=>head.map(k=>r[k]).join(',')).join('\n')],{type:'text/csv'}),'E1-E5_core9_frozen_Zscore_cells.csv')}
function exportLayout(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'E1-E5_selectable_radar_layout.json')}
async function importLayout(e){const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());state={...structuredClone(defaults),...x,colors:{...defaults.colors,...x.colors},panels:{...defaults.panels,...x.panels},featureLabels:{...defaults.featureLabels,...x.featureLabels}};sync();renderPanelControls();renderFeatureControls();render()}catch{status('The selected layout JSON could not be read.')}e.target.value=''}
async function init(){buildControls();const text=await fetch('data/radar_core9_cells.csv').then(r=>{if(!r.ok)throw Error(r.status);return r.text()});rows=parseCsv(text).map(r=>{for(const f of featureDefs)r[f.key]=+r[f.key];return r});if(rows.length!==450)throw Error(`Expected 450 cells, found ${rows.length}`);for(const c of classes)if(rows.filter(r=>r.E_class===c).length!==counts[c])throw Error(`Frozen ${c} count changed`);sync();render()}
init().catch(e=>status('Unable to load frozen radar data: '+e.message));
