#!/usr/bin/env python3
"""Create ten standalone audit figures for the HCxGC-consensus linear SVM.

The primary confusion/probability/ROC analyses use the frozen nested out-of-fold
predictions generated by train_hc_gc_consensus_eclass_ml.py. Diagnostic C scans,
repeated-CV stability, permutation testing, and coefficient stability use the
same fold-fitted preprocessing pipeline and the selected C=0.1.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import FancyBboxPatch
from scipy.stats import sem, t
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.metrics import (
    accuracy_score, auc, balanced_accuracy_score, cohen_kappa_score,
    confusion_matrix, f1_score, precision_recall_curve, precision_score,
    recall_score, roc_curve,
)
from sklearn.model_selection import RepeatedStratifiedKFold, StratifiedKFold
from sklearn.multiclass import OneVsRestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, label_binarize
from sklearn.svm import SVC


ROOT = Path(__file__).resolve().parents[1]
BASE = Path(os.environ.get(
    "MOUSE_E_SVM_BASE_OUT",
    ROOT / "outputs/e_type_qc/HC_GC_only/15_supervised_classifier_audit",
))
OUT = Path(os.environ.get(
    "MOUSE_E_SVM_SUPPORT_OUT",
    ROOT / "outputs/e_type_qc/HC_GC_only/25_SVM_supplementary_10_individual",
))
OUT.mkdir(parents=True, exist_ok=True)
FEATURE_FILE = ROOT / "outputs/e_type_qc/hc5_tree_distillation/NPC3_HC5_Raw_Final18_Features.csv"
ASSIGN_FILE = ROOT / "outputs/e_type_qc/HC_GC_only/HC_GC_only_cell_assignments.csv"
OOF_FILE = BASE / "NestedOOF_Linear_SVM_Predictions.csv"

SEED = 777
CLASSES = ["E1", "E2", "E3", "E4", "E5"]
COLORS = {"E1": "#4E79A7", "E2": "#F28E2B", "E3": "#59A14F", "E4": "#2AA6B8", "E5": "#B07AA1"}
FEATURE_LABELS = {
    "E_Holding.MP..mV.": "Holding MP", "E_Input.resistance..MOhm.": "Input resistance",
    "E_Membrane.time.constant..ms.": "Membrane tau", "E_Rheobase..pA.": "Rheobase",
    "E_Sag.ratio": "Sag ratio", "E_Sag.time..s.": "Sag time",
    "E_AP.threshold..mV.": "AP threshold", "E_AP.amplitude..mV.": "AP amplitude",
    "E_AP.width..ms.": "AP width", "E_Upstroke.to.downstroke.ratio": "Up/down ratio",
    "E_Afterhyperpolarization..mV.": "AHP", "E_Max.number.of.APs": "Max APs",
    "E_Latency..ms.": "Latency", "E_Latency....20pA.current..ms.": "Latency@20 pA",
    "E_ISI.adaptation.index": "ISI adaptation", "E_ISI.coefficient.of.variation": "ISI CV",
    "E_AP.amplitude.adaptation.index": "AP amp adaptation",
    "E_AP.coefficient.of.variation": "AP CV",
}


class TranscriptomeLikeTransformer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        a = np.asarray(X, float)
        self.minimum_ = np.nanmin(a, axis=0)
        shifted = np.maximum(a - self.minimum_, 0)
        self.column_sum_ = shifted.sum(axis=0)
        self.column_sum_[self.column_sum_ <= 0] = 1
        return self

    def transform(self, X):
        a = np.asarray(X, float)
        shifted = np.maximum(a - self.minimum_, 0)
        return np.log1p(shifted / self.column_sum_ * 10000)


def model(c=0.1, probability=False):
    return Pipeline([
        ("transform", TranscriptomeLikeTransformer()),
        ("scale", StandardScaler()),
        ("model", SVC(kernel="linear", C=c, class_weight="balanced",
                      probability=probability, random_state=SEED)),
    ])


def style():
    mpl.rcParams.update({
        "font.family": "Arial", "font.size": 6, "axes.linewidth": .55,
        "xtick.major.width": .5, "ytick.major.width": .5,
        "xtick.major.size": 2, "ytick.major.size": 2,
        "pdf.fonttype": 42, "ps.fonttype": 42,
    })


def save(fig, stem, w, h):
    fig.set_size_inches(w, h)
    fig.savefig(OUT / f"{stem}.png", dpi=900, facecolor="white", bbox_inches="tight", pad_inches=.04)
    fig.savefig(OUT / f"{stem}.pdf", facecolor="white", bbox_inches="tight", pad_inches=.04)
    plt.close(fig)


def load():
    feat = pd.read_csv(FEATURE_FILE)
    assign = pd.read_csv(ASSIGN_FILE)
    assign["HC_GC_consensus"] = assign.HC_GC_consensus.astype(str).str.lower().eq("true")
    df = feat.merge(assign, on="MSN_unique_ID", validate="one_to_one")
    df = df[df.HC_GC_consensus].reset_index(drop=True)
    features = [c for c in feat.columns if c != "MSN_unique_ID"]
    oof = pd.read_csv(OOF_FILE)
    df = df.merge(oof, on="MSN_unique_ID", validate="one_to_one")
    assert len(df) == 450 and len(features) == 18
    return df, features


def matrix_figures(df):
    cm = confusion_matrix(df.True_E, df.Predicted_E, labels=CLASSES)
    pct = cm / cm.sum(1, keepdims=True) * 100
    pd.DataFrame(cm, index=CLASSES, columns=CLASSES).to_csv(OUT / "01a_confusion_counts.csv")
    pd.DataFrame(pct, index=CLASSES, columns=CLASSES).to_csv(OUT / "01b_confusion_row_percent.csv")
    for arr, cmap, vmax, fmt, stem, title in [
        (cm, "Blues", cm.max(), lambda x: f"{int(x)}", "01a_confusion_raw_counts", "Nested OOF confusion: counts"),
        (pct, "Blues", 100, lambda x: f"{x:.1f}%", "01b_confusion_row_normalized", "Nested OOF confusion: row %"),
    ]:
        fig, ax = plt.subplots()
        im = ax.imshow(arr, cmap=cmap, vmin=0, vmax=vmax)
        for i in range(5):
            for j in range(5):
                ax.text(j, i, fmt(arr[i, j]), ha="center", va="center", fontsize=5,
                        color="white" if arr[i, j] > vmax*.52 else "black")
        ax.set_xticks(range(5), CLASSES); ax.set_yticks(range(5), CLASSES)
        ax.set_xlabel("SVM-predicted class"); ax.set_ylabel("HC × GC consensus class")
        ax.set_title(title + "\nN = 450; support = 142, 160, 45, 61, 42", fontsize=6)
        fig.colorbar(im, ax=ax, fraction=.047, pad=.04)
        save(fig, stem, 2.35, 2.15)


def main_panel(df):
    """Standalone version of the manuscript SVM panel."""
    cm = confusion_matrix(df.True_E, df.Predicted_E, labels=CLASSES)
    pct = cm / cm.sum(1, keepdims=True)
    fig = plt.figure()
    gs = fig.add_gridspec(1, 3, width_ratios=[.08, 1, .055], wspace=.08)
    axbar = fig.add_subplot(gs[0, 0]); ax = fig.add_subplot(gs[0, 1]); cax = fig.add_subplot(gs[0, 2])
    rgb = np.array([mpl.colors.to_rgb(COLORS[c]) for c in CLASSES]).reshape(5, 1, 3)
    axbar.imshow(rgb, aspect="auto"); axbar.set_xticks([]); axbar.set_yticks([])
    for s in axbar.spines.values(): s.set_visible(False)
    im = ax.imshow(pct, cmap="magma", vmin=0, vmax=1, interpolation="nearest")
    ax.set_xticks(range(5), CLASSES); ax.set_yticks(range(5), CLASSES)
    ax.set_xlabel("SVM-predicted class"); ax.set_ylabel("HC × GC consensus class")
    ax.set_title("Class-weighted linear SVM\nNested OOF accuracy: 92.0%", fontsize=6)
    cb = fig.colorbar(im, cax=cax); cb.set_ticks([0, .5, 1]); cb.set_label("Consensus identity probability", fontsize=5)
    save(fig, "00_main_SVM_confusion_panel", 2.15, 2.0)


def workflow():
    fig, ax = plt.subplots(); ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    boxes = [
        (.03, .72, .18, .17, "450 consensus cells\n18 frozen E-features"),
        (.28, .72, .18, .17, "Outer CV\nstratified 5-fold"),
        (.53, .72, .18, .17, "Inner CV\nstratified 4-fold\nC selection by BA"),
        (.78, .72, .18, .17, "Held-out prediction\nonce per cell"),
        (.28, .28, .43, .20, "Training-fold-only pipeline\nshift/normalize/log1p → z-score →\nclass-weighted linear SVM"),
    ]
    for x, y, w, h, txt in boxes:
        p = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.015", fc="#F4F4F4", ec="black", lw=.6)
        ax.add_patch(p); ax.text(x+w/2, y+h/2, txt, ha="center", va="center", fontsize=5.5)
    for x1, y1, x2, y2 in [(.21,.805,.28,.805),(.46,.805,.53,.805),(.71,.805,.78,.805),(.37,.72,.43,.48),(.62,.48,.87,.72)]:
        ax.annotate("", xy=(x2,y2), xytext=(x1,y1), arrowprops=dict(arrowstyle="->", lw=.6))
    ax.text(.5, .08, "No missing values; no imputation. Probabilities use SVC internal Platt scaling.\nNested OOF accuracy 92.0%; BA 93.2%; macro-F1 92.1%.", ha="center", fontsize=5.5)
    ax.set_title("Leakage-controlled nested cross-validation", fontsize=7)
    save(fig, "02_cross_validation_workflow", 5.8, 2.2)


def repeated_scan(X, y, c_values, repeats=10):
    cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=repeats, random_state=SEED)
    rows = []
    splits = list(cv.split(X, y))
    for c in c_values:
        for k, (tr, te) in enumerate(splits, 1):
            m = model(c).fit(X[tr], y[tr]); p = m.predict(X[te])
            rows.append({"C": c, "Fold": k, "Accuracy": accuracy_score(y[te], p),
                         "Balanced_accuracy": balanced_accuracy_score(y[te], p),
                         "Macro_F1": f1_score(y[te], p, average="macro"),
                         "Kappa": cohen_kappa_score(y[te], p)})
    return pd.DataFrame(rows)


def c_scan(scan):
    scan.to_csv(OUT / "03_C_scan_fold_metrics.csv", index=False)
    metrics = ["Accuracy", "Balanced_accuracy", "Macro_F1"]
    fig, ax = plt.subplots()
    for metric, col, marker in zip(metrics, ["#333333", "#4E79A7", "#F28E2B"], ["o","s","^"]):
        g = scan.groupby("C")[metric]
        mean, se = g.mean(), g.sem(); n = g.count().iloc[0]
        ci = t.ppf(.975, n-1) * se
        ax.errorbar(mean.index, mean, yerr=ci, marker=marker, ms=3, lw=.8, capsize=2, label=metric.replace("_", " "), color=col)
    ax.axvline(.1, ls="--", lw=.7, color="#B2182B"); ax.text(.1, .805, "selected C = 0.1", rotation=90, va="bottom", ha="right", color="#B2182B")
    ax.set_xscale("log"); ax.set_ylim(.78, 1.0); ax.set_xlabel("Linear SVM regularization parameter C"); ax.set_ylabel("Repeated held-out score")
    ax.legend(frameon=False, fontsize=5); ax.spines[["top","right"]].set_visible(False)
    ax.set_title("Repeated stratified 5-fold CV (10 repeats; mean ± 95% CI)")
    save(fig, "03_regularization_C_scan", 3.25, 2.35)


def class_performance(df):
    y, p = df.True_E.to_numpy(), df.Predicted_E.to_numpy(); cm = confusion_matrix(y,p,labels=CLASSES)
    rows=[]
    for i,c in enumerate(CLASSES):
        tp=cm[i,i]; fn=cm[i].sum()-tp; fp=cm[:,i].sum()-tp; tn=cm.sum()-tp-fn-fp
        rows.append({"Class":c,"Precision":tp/(tp+fp),"Recall_sensitivity":tp/(tp+fn),"Specificity":tn/(tn+fp),"F1":f1_score(y==c,p==c),"Support":cm[i].sum()})
    tab=pd.DataFrame(rows); tab.to_csv(OUT/"04_classwise_metrics.csv",index=False)
    fig,ax=plt.subplots(); x=np.arange(5); width=.19
    for k,(metric,color) in enumerate(zip(["Precision","Recall_sensitivity","Specificity","F1"],["#4E79A7","#F28E2B","#59A14F","#B07AA1"])):
        ax.bar(x+(k-1.5)*width,tab[metric],width,label=metric.replace("_sensitivity",""),color=color)
    ax.set_xticks(x,[f"{c}\n(n={n})" for c,n in zip(tab.Class,tab.Support)]); ax.set_ylim(.72,1.01); ax.set_ylabel("Nested OOF score")
    ax.legend(frameon=False,ncol=2,fontsize=5); ax.spines[["top","right"]].set_visible(False); ax.set_title("Class-wise performance")
    save(fig,"04_classwise_performance",3.3,2.35)


def roc_pr(df):
    y=df.True_E.to_numpy(); Y=label_binarize(y,classes=CLASSES); probs=df[[f"P_{c}" for c in CLASSES]].to_numpy()
    roc_rows=[]; pr_rows=[]; fig,axes=plt.subplots(1,2)
    for i,c in enumerate(CLASSES):
        fpr,tpr,_=roc_curve(Y[:,i],probs[:,i]); prec,rec,_=precision_recall_curve(Y[:,i],probs[:,i])
        ra=auc(fpr,tpr); pa=auc(rec[::-1],prec[::-1]); axes[0].plot(fpr,tpr,color=COLORS[c],lw=1,label=f"{c} ({ra:.3f})"); axes[1].plot(rec,prec,color=COLORS[c],lw=1,label=f"{c} ({pa:.3f})")
        roc_rows.append({"Class":c,"ROC_AUC":ra}); pr_rows.append({"Class":c,"PR_AUC":pa})
    fpr,tpr,_=roc_curve(Y.ravel(),probs.ravel()); prec,rec,_=precision_recall_curve(Y.ravel(),probs.ravel())
    micro_roc=auc(fpr,tpr); micro_pr=auc(rec[::-1],prec[::-1]); macro_roc=np.mean([r["ROC_AUC"] for r in roc_rows]); macro_pr=np.mean([r["PR_AUC"] for r in pr_rows])
    axes[0].plot([0,1],[0,1],ls="--",color=".6",lw=.6); axes[0].set(xlabel="False-positive rate",ylabel="True-positive rate",title=f"One-vs-rest ROC\nmicro={micro_roc:.3f}, macro={macro_roc:.3f}")
    axes[1].set(xlabel="Recall",ylabel="Precision",title=f"One-vs-rest precision–recall\nmicro={micro_pr:.3f}, macro={macro_pr:.3f}")
    for ax in axes: ax.set_xlim(0,1); ax.set_ylim(0,1.02); ax.legend(frameon=False,fontsize=4.5); ax.spines[["top","right"]].set_visible(False)
    pd.DataFrame(roc_rows).merge(pd.DataFrame(pr_rows),on="Class").to_csv(OUT/"05_ovr_auc_metrics.csv",index=False)
    save(fig,"05_one_vs_rest_ROC_PR",5.2,2.25)


def probability_heatmap(df):
    q=df.copy(); q["True_order"]=q.True_E.map({c:i for i,c in enumerate(CLASSES)}); q=q.sort_values(["True_order","Correct","Prediction_confidence"],ascending=[True,True,False])
    prob=q[[f"P_{c}" for c in CLASSES]].to_numpy(); fig,ax=plt.subplots(); im=ax.imshow(prob,aspect="auto",cmap="viridis",vmin=0,vmax=1,interpolation="nearest")
    starts=np.r_[0,np.cumsum(q.groupby("True_E",sort=False).size().to_numpy())];
    for s in starts[1:-1]: ax.axhline(s-.5,color="white",lw=.7)
    centers=(starts[:-1]+starts[1:]-1)/2; ax.set_yticks(centers,CLASSES); ax.set_xticks(range(5),CLASSES); ax.set_xlabel("SVM class probability"); ax.set_ylabel("True consensus class (cells sorted by confidence)")
    ax.set_title("Nested out-of-fold probability matrix\nincorrect predictions grouped first within each class"); fig.colorbar(im,ax=ax,label="Platt-scaled probability",fraction=.046,pad=.03)
    save(fig,"06_nested_OOF_probability_matrix",3.25,3.0)


def error_tsne(df):
    fig,ax=plt.subplots();
    for c in CLASSES:
        q=df[(df.True_E==c)&df.Correct]; ax.scatter(q.tSNE_1,q.tSNE_2,s=5,color=COLORS[c],alpha=.8,lw=0)
    bad=df[~df.Correct]; ax.scatter(bad.tSNE_1,bad.tSNE_2,s=18,facecolors="none",edgecolors="black",lw=.55,label=f"Incorrect (n={len(bad)})")
    ax.set_aspect(1/1.2); ax.set_xlabel("tSNE1"); ax.set_ylabel("tSNE2"); ax.legend(frameon=False,fontsize=5); ax.set_title("Nested OOF errors on fixed GC t-SNE coordinates")
    ax.spines[["top","right"]].set_visible(False); bad.to_csv(OUT/"07_misclassified_cells.csv",index=False)
    save(fig,"07_misclassified_cells_fixed_tSNE",2.45,2.5)


def stability(scan):
    metrics=["Accuracy","Balanced_accuracy","Macro_F1","Kappa"]; scan.to_csv(OUT/"08_repeated_CV_fold_metrics.csv",index=False)
    fig,ax=plt.subplots(); vals=[scan[m].to_numpy() for m in metrics]
    bp=ax.boxplot(vals,patch_artist=True,widths=.55,showfliers=False,medianprops=dict(color="black",lw=.7),boxprops=dict(lw=.6),whiskerprops=dict(lw=.6),capprops=dict(lw=.6))
    for b,c in zip(bp["boxes"],["#4E79A7","#F28E2B","#59A14F","#B07AA1"]): b.set_facecolor(c); b.set_alpha(.45)
    rng=np.random.default_rng(SEED)
    for i,v in enumerate(vals,1): ax.scatter(i+rng.uniform(-.18,.18,len(v)),v,s=3,color=".25",alpha=.25,lw=0)
    ax.set_xticks(range(1,5),["Accuracy","Balanced\naccuracy","Macro-F1","Cohen's κ"]); ax.set_ylim(.68,1.01); ax.set_ylabel("Held-out fold score"); ax.set_title("Fixed C = 0.1: repeated stratified 5-fold CV\n10 repeats, 50 held-out folds")
    ax.spines[["top","right"]].set_visible(False); save(fig,"08_repeated_CV_stability",3.2,2.35)


def permutation(X,y,n_perm=999):
    cv=StratifiedKFold(5,shuffle=True,random_state=SEED); splits=list(cv.split(X,y))
    obs=[]
    for tr,te in splits:
        p=model(.1).fit(X[tr],y[tr]).predict(X[te]); obs.append(balanced_accuracy_score(y[te],p))
    observed=np.mean(obs); rng=np.random.default_rng(SEED); null=[]
    for _ in range(n_perm):
        yp=rng.permutation(y); scores=[]
        for tr,te in splits:
            p=model(.1).fit(X[tr],yp[tr]).predict(X[te]); scores.append(balanced_accuracy_score(yp[te],p))
        null.append(np.mean(scores))
    null=np.array(null); pval=(1+np.sum(null>=observed))/(n_perm+1)
    pd.DataFrame({"Permutation":np.arange(1,n_perm+1),"Null_balanced_accuracy":null}).to_csv(OUT/"09_permutation_null.csv",index=False)
    (OUT/"09_permutation_summary.json").write_text(json.dumps({"Observed_mean_fold_balanced_accuracy":observed,"N_permutations":n_perm,"Empirical_P":pval},indent=2))
    fig,ax=plt.subplots(); ax.hist(null,bins=28,color="#BDBDBD",edgecolor="white",lw=.3); ax.axvline(observed,color="#B2182B",lw=1.2,label=f"Observed = {observed:.3f}\nP = {pval:.3g}")
    ax.set_xlabel("Mean 5-fold balanced accuracy"); ax.set_ylabel("Permutations"); ax.set_title("Label-permutation test (fixed C = 0.1)"); ax.legend(frameon=False,fontsize=5); ax.spines[["top","right"]].set_visible(False)
    save(fig,"09_label_permutation_test",3.15,2.3)


def coefficient_heatmap(X,y,features,repeats=10):
    cv=RepeatedStratifiedKFold(n_splits=5,n_repeats=repeats,random_state=SEED); coefs=[]
    for tr,te in cv.split(X,y):
        m=Pipeline([
            ("transform", TranscriptomeLikeTransformer()),
            ("scale", StandardScaler()),
            ("model", OneVsRestClassifier(SVC(kernel="linear", C=.1, class_weight="balanced", random_state=SEED))),
        ]).fit(X[tr],y[tr])
        coefs.append(np.vstack([est.coef_[0] for est in m.named_steps["model"].estimators_]))
    arr=np.stack(coefs); mean=arr.mean(0); sd=arr.std(0,ddof=1)
    labels=[FEATURE_LABELS.get(f,f) for f in features];
    pd.DataFrame(mean,index=CLASSES,columns=labels).to_csv(OUT/"10_linear_SVM_standardized_coefficients_mean.csv")
    pd.DataFrame(sd,index=CLASSES,columns=labels).to_csv(OUT/"10_linear_SVM_standardized_coefficients_sd.csv")
    vmax=np.quantile(np.abs(mean),.98); fig,ax=plt.subplots(); im=ax.imshow(mean,cmap="RdBu_r",vmin=-vmax,vmax=vmax,aspect="auto")
    ax.set_xticks(range(len(labels)),labels,rotation=65,ha="right"); ax.set_yticks(range(5),CLASSES); ax.set_ylabel("One-vs-rest decision function"); ax.set_title("Signed one-vs-rest linear-SVM coefficients\npost hoc surrogate; mean across 50 training folds")
    fig.colorbar(im,ax=ax,label="Signed coefficient",fraction=.025,pad=.02); save(fig,"10_signed_linear_SVM_feature_weights",6.1,2.4)


def main():
    style(); df,features=load(); X=df[features].to_numpy(float); y=df.True_E.to_numpy()
    matrix_figures(df); workflow()
    scan=repeated_scan(X,y,[.01,.03,.1,.3,1,3,10],10); c_scan(scan)
    class_performance(df); roc_pr(df); probability_heatmap(df); error_tsne(df)
    stability(scan[scan.C.eq(.1)].copy()); permutation(X,y,999); coefficient_heatmap(X,y,features,10)
    summary={"N":450,"Support":df.True_E.value_counts().sort_index().to_dict(),"Nested_OOF_accuracy":accuracy_score(df.True_E,df.Predicted_E),"Nested_OOF_balanced_accuracy":balanced_accuracy_score(df.True_E,df.Predicted_E),"Nested_OOF_macro_F1":f1_score(df.True_E,df.Predicted_E,average="macro"),"Selected_C":.1,"Seed":SEED}
    (OUT/"00_analysis_summary.json").write_text(json.dumps(summary,indent=2),encoding="utf-8")
    print(json.dumps(summary,indent=2)); print(OUT)


if __name__ == "__main__":
    main()
