const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const el=(tag,a={},text='')=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
const quantile=(a,q)=>{const s=[...a].sort((x,y)=>x-y),p=(s.length-1)*q,i=Math.floor(p),r=p-i;return s[i]+(s[i+1]??s[i]-s[i])*r};
const extent=a=>[Math.min(...a),Math.max(...a)],fmt=v=>Math.abs(v)>=100?Math.round(v):Math.abs(v)>=1?v.toFixed(2).replace(/\.00$/,''):v.toFixed(2);
function csv(text){const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){field+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x!==''))rows.push(row);row=[];field=''}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const h=rows.shift();return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
const load=async name=>csv(await fetch(`ml-data/${name}`).then(r=>{if(!r.ok)throw Error(name);return r.text()}));
const niceDomain=a=>{let[lo,hi]=extent(a.filter(Number.isFinite));if(lo===hi){lo-=.5;hi+=.5}const d=(hi-lo)*.08;return[lo-d,hi+d]};
const ticks=(lo,hi,n=5)=>Array.from({length:n},(_,i)=>lo+(hi-lo)*i/(n-1));
const modelOrder=['Extra trees','kNN','RBF SVM','Linear SVM','Multinomial logistic','Random forest','HistGradientBoosting'];
const short={'Extra trees':'ET','RBF SVM':'RBF','Linear SVM':'Linear','Multinomial logistic':'Logit','Random forest':'RF','HistGradientBoosting':'HGB','KMeans':'KMeans','Gaussian mixture':'GMM'};
const className=c=>String(c);
const groupBy=(rows,key)=>rows.reduce((out,row)=>((out[key(row)]??=[]).push(row),out),{});
const basePanels=[
 ['a','ba','Held-out balanced accuracy','#149174','#0d5f52'],['b','f1','Held-out macro-F1','#149174','#0d5f52'],
 ['c','confusion','Confusion (%)','#154a86','#eef5fb'],['d','permutation','Permutation control','#bdbdbd','#e76f00'],
 ['e','roc','One-vs-rest ROC (AUC)','#4c78a8','#999999'],['f','pr','One-vs-rest PR (AP)','#4c78a8','#999999'],
 ['g','sensitivity','NPC and K sensitivity','#245685','#f7e225'],['h','discovery','Experimental-day-resampled discovery','#a9c8d6','#6e7c82'],
 ['i','agreement','Full-data algorithm agreement','#4c78a8','#274d72'],['j','margin','Cell-level consensus margin','#6e98bd','#e76f00'],
 ['k','classmargin','Assignment stability by class','#4c78a8','#333333'],['l','metadata','Association with metadata','#909090','#404040'],
 ['m','importance','Train-only permutation importance','#4c78a8','#222222'],['n','mdi','MDI stability (500 held-day splits)','#52b8e8','#222222'],
 ['o','rank','Cross-model rank agreement','#0586be','#9c9c9c'],['p','ablation','Progressive feature ablation','#149174','#777777']
];
const state={canvasW:1600,canvasH:930,columns:4,gapX:22,gapY:22,background:'#ffffff',fontFamily:'Arial',titleSize:15,letterSize:16,axisSize:11,lineWidth:1,pointSize:3,pointOpacity:.8,
 colors:{M1:'#00468B',M2:'#42B540',M3:'#ED0000',M4:'#0099B4',model:'#149174',bar:'#4C78A8',neutral:'#BDBDBD',accent:'#E76F00',heatLow:'#203B74',heatHigh:'#F6E928'},panels:[],selected:'ba'};
basePanels.forEach(([letter,id,title,color,color2],i)=>state.panels.push({letter,id,title,color,color2,visible:true,x:20+(i%4)*390,y:20+Math.floor(i/4)*225,w:365,h:205,xMin:null,xMax:null,yMin:null,yMax:null,titleDx:0,titleDy:0,letterDx:0,letterDy:0,xLabelDx:0,xLabelDy:0,yLabelDx:0,yLabelDy:0}));
let D={},drag=null;

function plotRect(p,left=47,right=12,top=29,bottom=37){return{x:left,y:top,w:p.w-left-right,h:p.h-top-bottom}}
function scales(p,rawX,rawY,r=plotRect(p)){
 const xd=[p.xMin??rawX[0],p.xMax??rawX[1]],yd=[p.yMin??rawY[0],p.yMax??rawY[1]];
 return{r,xd,yd,X:v=>r.x+(v-xd[0])/(xd[1]-xd[0]||1)*r.w,Y:v=>r.y+r.h-(v-yd[0])/(yd[1]-yd[0]||1)*r.h};
}
function textNode(g,p,kind,text,x,y,a={}){const n=el('text',{x,y,'font-family':state.fontFamily,'font-size':a.size??state.axisSize,'font-weight':a.weight??'normal','text-anchor':a.anchor??'middle',fill:a.fill??'#141b20',class:'draggable-text',...a},text);n.dataset.kind=kind;n.dataset.panel=p.id;g.append(n);return n}
function frame(g,p,xlabel='',ylabel='',xTicks=[],yTicks=[],xCats=null,domains=null){const r=plotRect(p),s=domains??scales(p,[0,1],[0,1],r);g.append(el('path',{d:`M${r.x},${r.y}V${r.y+r.h}H${r.x+r.w}`,fill:'none',stroke:'#222','stroke-width':state.lineWidth}));
 yTicks.forEach(v=>{if(v<s.yd[0]||v>s.yd[1])return;const y=s.Y(v);g.append(el('line',{x1:r.x-4,x2:r.x,y1:y,y2:y,stroke:'#222','stroke-width':state.lineWidth}));textNode(g,p,'none',fmt(v),r.x-7,y+3,{anchor:'end',size:state.axisSize,fill:'#273139'})});
 if(xCats){xCats.forEach((v,i)=>{const x=r.x+(i+.5)*r.w/xCats.length;g.append(el('line',{x1:x,x2:x,y1:r.y+r.h,y2:r.y+r.h+4,stroke:'#222','stroke-width':state.lineWidth}));textNode(g,p,'none',v,x,r.y+r.h+14,{size:state.axisSize,fill:'#273139',transform:`rotate(-25 ${x} ${r.y+r.h+14})`})})}
 else xTicks.forEach(v=>{if(v<s.xd[0]||v>s.xd[1])return;const x=s.X(v);g.append(el('line',{x1:x,x2:x,y1:r.y+r.h,y2:r.y+r.h+4,stroke:'#222','stroke-width':state.lineWidth}));textNode(g,p,'none',fmt(v),x,r.y+r.h+14,{size:state.axisSize,fill:'#273139'})});
 if(xlabel)textNode(g,p,'xLabel',xlabel,r.x+r.w/2+p.xLabelDx,p.h-3+p.xLabelDy,{size:state.axisSize});
 if(ylabel)textNode(g,p,'yLabel',ylabel,10+p.yLabelDx,r.y+r.h/2+p.yLabelDy,{size:state.axisSize,transform:`rotate(-90 ${10+p.yLabelDx} ${r.y+r.h/2+p.yLabelDy})`});return s}
function box(g,values,x,r,s,color,width=.56){if(!values.length)return;const q1=quantile(values,.25),q2=quantile(values,.5),q3=quantile(values,.75),iq=q3-q1,lo=Math.max(Math.min(...values),q1-1.5*iq),hi=Math.min(Math.max(...values),q3+1.5*iq),bw=r.w/Math.max(1,width?8:1)*width;g.append(el('line',{x1:x,x2:x,y1:s.Y(lo),y2:s.Y(hi),stroke:'#3d474d','stroke-width':state.lineWidth}));g.append(el('rect',{x:x-bw/2,y:s.Y(q3),width:bw,height:Math.max(1,s.Y(q1)-s.Y(q3)),fill:color,'fill-opacity':.65,stroke:'#38434a','stroke-width':state.lineWidth}));g.append(el('line',{x1:x-bw/2,x2:x+bw/2,y1:s.Y(q2),y2:s.Y(q2),stroke:'#152027','stroke-width':state.lineWidth*1.3}));g.append(el('line',{x1:x-bw*.25,x2:x+bw*.25,y1:s.Y(lo),y2:s.Y(lo),stroke:'#3d474d'}));g.append(el('line',{x1:x-bw*.25,x2:x+bw*.25,y1:s.Y(hi),y2:s.Y(hi),stroke:'#3d474d'}))}
function boxes(g,p,groups,ylabel,colors=null){const cats=Object.keys(groups),all=Object.values(groups).flat(),yd=niceDomain(all),r=plotRect(p),s=scales(p,[0,cats.length],yd,r);cats.forEach((c,i)=>box(g,groups[c],r.x+(i+.5)*r.w/cats.length,r,s,colors?.[c]??p.color,.9));frame(g,p,'',ylabel,[],ticks(s.yd[0],s.yd[1]),cats,s)}
function kde(values,grid){const sd=Math.sqrt(mean(values.map(v=>(v-mean(values))**2)))||1,bw=Math.max(sd*.28,.02);return grid.map(x=>mean(values.map(v=>Math.exp(-.5*((x-v)/bw)**2))))}
function violin(g,p,groups,ylabel,colors=null){const cats=Object.keys(groups),all=Object.values(groups).flat(),yd=niceDomain(all),r=plotRect(p),s=scales(p,[0,cats.length],yd,r),grid=Array.from({length:45},(_,i)=>s.yd[0]+(s.yd[1]-s.yd[0])*i/44);cats.forEach((c,i)=>{const den=kde(groups[c],grid),mx=Math.max(...den),cx=r.x+(i+.5)*r.w/cats.length,hw=r.w/cats.length*.34,pts=grid.map((v,j)=>[cx-den[j]/mx*hw,s.Y(v)]),back=[...grid].reverse().map((v,j)=>[cx+den[den.length-1-j]/mx*hw,s.Y(v)]),d=[...pts,...back];g.append(el('path',{d:`M${d.map(q=>q.join(',')).join('L')}Z`,fill:colors?.[c]??p.color,'fill-opacity':.88,stroke:'#444','stroke-width':state.lineWidth}));box(g,groups[c],cx,r,s,'white',.28)});frame(g,p,'',ylabel,[],ticks(s.yd[0],s.yd[1]),cats,s)}
function hist(g,p,values,xlabel,marker=null){const xd=niceDomain(values.concat(marker==null?[]:[marker])),bins=24,w=(xd[1]-xd[0])/bins,counts=Array(bins).fill(0);values.forEach(v=>counts[clamp(Math.floor((v-xd[0])/w),0,bins-1)]++);const yd=[0,Math.max(...counts)*1.08],r=plotRect(p),s=scales(p,xd,yd,r);counts.forEach((v,i)=>g.append(el('rect',{x:s.X(xd[0]+i*w)+.3,y:s.Y(v),width:Math.max(1,s.X(xd[0]+(i+1)*w)-s.X(xd[0]+i*w)-.6),height:s.Y(0)-s.Y(v),fill:p.color})));if(marker!=null)g.append(el('line',{x1:s.X(marker),x2:s.X(marker),y1:r.y,y2:r.y+r.h,stroke:p.color2,'stroke-width':2}));frame(g,p,xlabel,'Count',ticks(s.xd[0],s.xd[1]),ticks(s.yd[0],s.yd[1]),null,s)}
function linePlot(g,p,rows,xk,yk,xlabel,ylabel,group='Class'){const groups=groupBy(rows,r=>className(r[group])),r=plotRect(p),s=scales(p,[0,1],[0,1],r);for(const[name,a]of Object.entries(groups)){const pts=a.map(q=>[s.X(+q[xk]),s.Y(+q[yk])]);g.append(el('path',{d:`M${pts.map(q=>q.join(',')).join('L')}`,fill:'none',stroke:state.colors[name]??p.color,'stroke-width':state.lineWidth*1.5}));const last=pts[Math.floor(pts.length*.7)]??pts.at(-1);if(last)textNode(g,p,'none',name,last[0]+4,last[1]-3,{anchor:'start',size:state.axisSize-1,fill:state.colors[name]??p.color})}g.append(el('line',{x1:s.X(0),x2:s.X(1),y1:s.Y(0),y2:s.Y(1),stroke:'#999','stroke-dasharray':'4 3'}));frame(g,p,xlabel,ylabel,ticks(0,1),ticks(0,1),null,s)}
function renderChart(g,p){if(p.id==='ba'||p.id==='f1'){const key=p.id==='ba'?'balanced_accuracy':'macro_F1',gr=Object.fromEntries(modelOrder.map(m=>[short[m]??m,D.supervised.filter(r=>r.algorithm===m).map(r=>+r[key])]));boxes(g,p,gr,key==='balanced_accuracy'?'Balanced accuracy':'Macro F1')}
 else if(p.id==='confusion'){const rows=D.confusion,cats=['M1','M2','M3','M4'],vals=rows.map(r=>cats.map(c=>+r[`pred_${c}`])),perc=vals.map(a=>a.map(v=>100*v/a.reduce((s,q)=>s+q,0))),r=plotRect(p,48,10,30,35),cw=r.w/4,ch=r.h/4;perc.forEach((a,i)=>a.forEach((v,j)=>{const t=v/100,c=mix('#f4f8fc',p.color,t);g.append(el('rect',{x:r.x+j*cw,y:r.y+i*ch,width:cw,height:ch,fill:c,stroke:'#fff'}));textNode(g,p,'none',Math.round(v),r.x+(j+.5)*cw,r.y+(i+.58)*ch,{size:state.axisSize,fill:t>.55?'#fff':'#26323a'})}));cats.forEach((c,i)=>{textNode(g,p,'none',c,r.x+(i+.5)*cw,r.y+r.h+14,{size:state.axisSize});textNode(g,p,'none',c,r.x-7,r.y+(i+.58)*ch,{anchor:'end',size:state.axisSize})});textNode(g,p,'xLabel','Predicted class',r.x+r.w/2+p.xLabelDx,p.h-3+p.xLabelDy,{size:state.axisSize});textNode(g,p,'yLabel','Frozen class',10+p.yLabelDx,r.y+r.h/2+p.yLabelDy,{size:state.axisSize,transform:`rotate(-90 ${10+p.yLabelDx} ${r.y+r.h/2+p.yLabelDy})`})}
 else if(p.id==='permutation')hist(g,p,D.permutation.map(r=>+r.mean_balanced_accuracy),'Balanced accuracy',+D.permSummary[0].observed_mean_balanced_accuracy);
 else if(p.id==='roc')linePlot(g,p,D.roc,'FPR','TPR','False-positive rate','True-positive rate');
 else if(p.id==='pr')linePlot(g,p,D.pr,'Recall','Precision','Recall','Precision');
 else if(p.id==='sensitivity'){const rows=D.sensitivity,npcs=[...new Set(rows.map(r=>+r.NPC))].sort((a,b)=>a-b),ks=[...new Set(rows.map(r=>+r.K))].sort((a,b)=>a-b),r=plotRect(p,43,28,30,34),cw=r.w/ks.length,ch=r.h/npcs.length;rows.forEach(q=>{const i=npcs.indexOf(+q.NPC),j=ks.indexOf(+q.K),v=+q.ARI_median,c=mix(p.color,p.color2,clamp(v/.8,0,1));g.append(el('rect',{x:r.x+j*cw,y:r.y+i*ch,width:cw,height:ch,fill:c,stroke:(+q.NPC===3&&+q.K===4)?'#fff':'none','stroke-width':2}));textNode(g,p,'none',v.toFixed(2),r.x+(j+.5)*cw,r.y+(i+.62)*ch,{size:Math.max(6,state.axisSize-2),fill:v>.48?'#13202a':'#fff'})});ks.forEach((v,i)=>textNode(g,p,'none',v,r.x+(i+.5)*cw,r.y+r.h+14,{size:state.axisSize}));npcs.forEach((v,i)=>textNode(g,p,'none',v,r.x-7,r.y+(i+.62)*ch,{anchor:'end',size:state.axisSize}));textNode(g,p,'xLabel','K',r.x+r.w/2+p.xLabelDx,p.h-3+p.xLabelDy,{size:state.axisSize});textNode(g,p,'yLabel','NPC',10+p.yLabelDx,r.y+r.h/2+p.yLabelDy,{size:state.axisSize,transform:`rotate(-90 ${10+p.yLabelDx} ${r.y+r.h/2+p.yLabelDy})`})}
 else if(p.id==='discovery'){const algs=['Ward','K-means','Gaussian mixture','Spectral'],gr=Object.fromEntries(algs.map(a=>[short[a]??a,D.discovery.filter(r=>r.algorithm===a).map(r=>+r.ARI_vs_reference)]));violin(g,p,gr,'ARI vs frozen M1–M4')}
 else if(p.id==='agreement'){const rows=D.agreement.filter(r=>r.algorithm_A==='Ward'||r.algorithm_B==='Ward'),gr={};rows.forEach(r=>{const k=r.algorithm_A==='Ward'?r.algorithm_B:r.algorithm_A;if(k!=='Ward')gr[k==='Frozen_HC'?'Ward':(short[k]??k)]=+r.ARI});bars(g,p,gr,'ARI vs frozen HC')}
 else if(p.id==='margin')hist(g,p,D.consensus.map(r=>+r.consensus_margin),'Within-class minus max other-class co-clustering probability',0);
 else if(p.id==='classmargin'){const gr=Object.fromEntries(['M1','M2','M3','M4'].map(c=>[c,D.consensus.filter(r=>r.reference_class===c).map(r=>+r.consensus_margin)]));violin(g,p,gr,'Consensus margin',state.colors)}
 else if(p.id==='metadata'){const gr={};D.metadata.forEach(r=>gr[r.metadata.replace('Lib_region_of_interest_label','ROI').replace('_label','')]=+r.cramers_v_bias_corrected);bars(g,p,gr,"Bias-corrected Cramér's V",true)}
 else if(p.id==='importance')hbars(g,p,D.trainImp.map(r=>({name:cleanFeature(r.feature),v:+r.relative_importance,lo:Math.max(0,+r.relative_importance-(+r.std||0)),hi:+r.relative_importance+(+r.std||0)})).sort((a,b)=>b.v-a.v),'Relative importance');
 else if(p.id==='mdi')hbars(g,p,D.mdi.map(r=>({name:cleanFeature(r.feature),v:+r.ExtraTrees_median,lo:+r.ExtraTrees_q025,hi:+r.ExtraTrees_q975})).sort((a,b)=>b.v-a.v),'Extra Trees MDI');
 else if(p.id==='rank'){const a=[...D.mdi].sort((x,y)=>+y.ExtraTrees_median-+x.ExtraTrees_median),b=[...D.mdi].sort((x,y)=>+y.Logistic_abscoef_median-+x.Logistic_abscoef_median),rb=Object.fromEntries(b.map((r,i)=>[r.feature,i+1])),pts=a.map((r,i)=>[i+1,rb[r.feature]]),r=plotRect(p),s=scales(p,[1,10],[1,10],r);g.append(el('line',{x1:s.X(1),x2:s.X(10),y1:s.Y(1),y2:s.Y(10),stroke:p.color2,'stroke-dasharray':'4 3'}));pts.forEach(q=>g.append(el('circle',{cx:s.X(q[0]),cy:s.Y(q[1]),r:state.pointSize,fill:p.color,'fill-opacity':state.pointOpacity})));frame(g,p,'Extra Trees rank','Logistic coefficient rank',ticks(1,10,5),ticks(1,10,5),null,s)}
 else if(p.id==='ablation'){const order=['All 10 features','Removing top 2','Removing top 5','Retaining bottom 3'],gr=Object.fromEntries(order.map(k=>[k.replace('Removing ','− ').replace('Retaining ','Retain '),D.ablation.filter(r=>r.subset===k).map(r=>+r.balanced_accuracy)]));boxes(g,p,gr,'Balanced accuracy');const r=plotRect(p),yd=niceDomain(Object.values(gr).flat()),s=scales(p,[0,4],yd,r);g.append(el('line',{x1:r.x,x2:r.x+r.w,y1:s.Y(.25),y2:s.Y(.25),stroke:p.color2,'stroke-dasharray':'3 3'}))}
}
function bars(g,p,obj,ylabel,horizontal=false){if(horizontal){const rows=Object.entries(obj),vals=rows.map(x=>x[1]),xd=niceDomain([0,...vals]),r=plotRect(p,55,15,30,35),s=scales(p,xd,[0,rows.length],r);rows.forEach(([k,v],i)=>{const y=r.y+(i+.15)*r.h/rows.length,h=r.h/rows.length*.7;g.append(el('rect',{x:s.X(0),y,width:s.X(v)-s.X(0),height:h,fill:p.color}));textNode(g,p,'none',k,r.x-6,y+h*.65,{anchor:'end',size:state.axisSize-1})});frame(g,p,ylabel,'',ticks(s.xd[0],s.xd[1]),[],null,s)}else{const cats=Object.keys(obj),vals=Object.values(obj),yd=niceDomain([0,...vals]),r=plotRect(p),s=scales(p,[0,cats.length],yd,r);cats.forEach((c,i)=>{const x=r.x+(i+.18)*r.w/cats.length,w=r.w/cats.length*.64;g.append(el('rect',{x,y:s.Y(obj[c]),width:w,height:s.Y(0)-s.Y(obj[c]),fill:p.color}))});frame(g,p,'',ylabel,[],ticks(s.yd[0],s.yd[1]),cats,s)}}
function hbars(g,p,rows,xlabel){const top=rows.slice(0,10).reverse(),xd=niceDomain([0,...top.flatMap(r=>[r.lo,r.hi])]),r=plotRect(p,122,14,29,34),s=scales(p,xd,[0,top.length],r),bh=r.h/top.length*.64;top.forEach((q,i)=>{const y=r.y+(i+.18)*r.h/top.length;g.append(el('rect',{x:s.X(0),y,width:s.X(q.v)-s.X(0),height:bh,fill:p.color}));g.append(el('line',{x1:s.X(q.lo),x2:s.X(q.hi),y1:y+bh/2,y2:y+bh/2,stroke:p.color2,'stroke-width':state.lineWidth}));textNode(g,p,'none',q.name,r.x-5,y+bh*.72,{anchor:'end',size:Math.max(5,state.axisSize-3)})});frame(g,p,xlabel,'',ticks(s.xd[0],s.xd[1]),[],null,s)}
function cleanFeature(s){return s.replace(/^M_/,'').replaceAll('_',' ')}
function mix(a,b,t){const A=a.match(/\w\w/g).map(x=>parseInt(x,16)),B=b.match(/\w\w/g).map(x=>parseInt(x,16));return'#'+A.map((v,i)=>Math.round(v+(B[i]-v)*t).toString(16).padStart(2,'0')).join('')}
function render(){const svg=$('figure');svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${state.canvasW} ${state.canvasH}`);svg.setAttribute('width',state.canvasW);svg.setAttribute('height',state.canvasH);svg.style.background=state.background;for(const p of state.panels){if(!p.visible)continue;const g=el('g',{class:`panel${p.id===state.selected?' selected':''}`,transform:`translate(${p.x} ${p.y})`});g.dataset.id=p.id;g.append(el('rect',{class:'panel-border',x:0,y:0,width:p.w,height:p.h}));g.append(el('rect',{class:'panel-hit',x:0,y:0,width:p.w,height:p.h,'data-panel':p.id,'data-drag':'panel'}));renderChart(g,p);textNode(g,p,'letter',p.letter,4+p.letterDx,15+p.letterDy,{anchor:'start',size:state.letterSize,weight:'bold'});textNode(g,p,'title',p.title,p.w/2+p.titleDx,17+p.titleDy,{size:state.titleSize});g.append(el('rect',{class:'resize-handle',x:p.w-8,y:p.h-8,width:8,height:8,'data-panel':p.id,'data-drag':'resize'}));svg.append(g)}bindSvg();syncControls();}
function bindSvg(){const svg=$('figure');svg.querySelectorAll('[data-panel]').forEach(n=>n.addEventListener('pointerdown',e=>{const p=panel(e.currentTarget.dataset.panel);state.selected=p.id;drag={kind:e.currentTarget.dataset.drag,p,startX:e.clientX,startY:e.clientY,x:p.x,y:p.y,w:p.w,h:p.h};syncControls();e.preventDefault()}));svg.querySelectorAll('.draggable-text').forEach(n=>n.addEventListener('pointerdown',e=>{const kind=e.currentTarget.dataset.kind;if(kind==='none')return;const p=panel(e.currentTarget.dataset.panel);state.selected=p.id;drag={kind,p,startX:e.clientX,startY:e.clientY};syncControls();e.stopPropagation();e.preventDefault()}))}
window.addEventListener('pointermove',e=>{if(!drag)return;const svg=$('figure'),box=svg.getBoundingClientRect(),sx=state.canvasW/box.width,sy=state.canvasH/box.height,dx=(e.clientX-drag.startX)*sx,dy=(e.clientY-drag.startY)*sy,p=drag.p;if(drag.kind==='panel'){p.x=Math.round(drag.x+dx);p.y=Math.round(drag.y+dy)}else if(drag.kind==='resize'){p.w=Math.max(180,Math.round(drag.w+dx));p.h=Math.max(140,Math.round(drag.h+dy))}else{const xKey={title:'titleDx',letter:'letterDx',xLabel:'xLabelDx',yLabel:'yLabelDx'}[drag.kind],yKey={title:'titleDy',letter:'letterDy',xLabel:'xLabelDy',yLabel:'yLabelDy'}[drag.kind];p[xKey]=Math.round((p[xKey]||0)+dx);p[yKey]=Math.round((p[yKey]||0)+dy);drag.startX=e.clientX;drag.startY=e.clientY}render()});window.addEventListener('pointerup',()=>drag=null);window.addEventListener('pointercancel',()=>drag=null);
const panel=id=>state.panels.find(p=>p.id===id);
function syncControls(){const p=panel(state.selected);$('panelSelect').value=p.id;for(const k of['x','y','w','h','titleDx','titleDy','letterDx','letterDy','xLabelDx','xLabelDy','yLabelDx','yLabelDy'])$(k).value=p[k];for(const k of['xMin','xMax','yMin','yMax'])$(k).value=p[k]??'';$('visible').checked=p.visible;$('panelColor').value=p.color;$('panelColor2').value=p.color2;for(const k of['canvasW','canvasH','columns','gapX','gapY','background','fontFamily','titleSize','letterSize','axisSize','lineWidth','pointSize','pointOpacity'])$(k).value=state[k]}
function controls(){$('panelSelect').innerHTML=state.panels.map(p=>`<option value="${p.id}">${p.letter} · ${p.title}</option>`).join('');$('colors').innerHTML=Object.entries(state.colors).map(([k,v])=>`<label>${k}<input type="color" data-color="${k}" value="${v}"></label>`).join('');$('panelSelect').onchange=e=>{state.selected=e.target.value;render()};for(const k of['x','y','w','h','titleDx','titleDy','letterDx','letterDy','xLabelDx','xLabelDy','yLabelDx','yLabelDy'])$(k).oninput=e=>{panel(state.selected)[k]=+e.target.value;render()};for(const k of['xMin','xMax','yMin','yMax'])$(k).onchange=e=>{panel(state.selected)[k]=e.target.value===''?null:+e.target.value;render()};$('visible').onchange=e=>{panel(state.selected).visible=e.target.checked;render()};$('panelColor').oninput=e=>{panel(state.selected).color=e.target.value;render()};$('panelColor2').oninput=e=>{panel(state.selected).color2=e.target.value;render()};for(const k of['canvasW','canvasH','columns','gapX','gapY','titleSize','letterSize','axisSize','lineWidth','pointSize','pointOpacity'])$(k).oninput=e=>{state[k]=+e.target.value;render()};for(const k of['background','fontFamily'])$(k).oninput=e=>{state[k]=e.target.value;render()};document.querySelectorAll('[data-color]').forEach(n=>n.oninput=e=>{state.colors[e.target.dataset.color]=e.target.value;render()});$('fitAxes').onclick=()=>{Object.assign(panel(state.selected),{xMin:null,xMax:null,yMin:null,yMax:null});render()};$('front').onclick=()=>{const i=state.panels.findIndex(p=>p.id===state.selected);state.panels.push(state.panels.splice(i,1)[0]);render()};$('autoLayout').onclick=autoLayout;$('reset').onclick=()=>location.reload();$('exportSvg').onclick=exportSvg;$('exportPng').onclick=exportPng;$('exportLayout').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'Mouse_M1-M4_ML_layout.json');$('importLayout').onchange=importLayout}
function autoLayout(){const vis=state.panels.filter(p=>p.visible),cols=state.columns,w=Math.floor((state.canvasW-40-state.gapX*(cols-1))/cols),rows=Math.ceil(vis.length/cols),h=Math.floor((state.canvasH-40-state.gapY*(rows-1))/rows);vis.forEach((p,i)=>Object.assign(p,{x:20+(i%cols)*(w+state.gapX),y:20+Math.floor(i/cols)*(h+state.gapY),w,h}));render()}
function svgText(){const clone=$('figure').cloneNode(true);clone.querySelectorAll('.panel-hit,.resize-handle,.panel-border').forEach(n=>n.remove());clone.setAttribute('xmlns',NS);return new XMLSerializer().serializeToString(clone)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportSvg(){download(new Blob([svgText()],{type:'image/svg+xml'}),'Mouse_M1-M4_ML_interactive_export.svg')}
function exportPng(){const img=new Image(),url=URL.createObjectURL(new Blob([svgText()],{type:'image/svg+xml'})),scale=+$('pngScale').value;img.onload=()=>{const c=document.createElement('canvas');c.width=state.canvasW*scale;c.height=state.canvasH*scale;const x=c.getContext('2d');x.scale(scale,scale);x.drawImage(img,0,0);c.toBlob(b=>download(b,'Mouse_M1-M4_ML_interactive_export.png'),'image/png');URL.revokeObjectURL(url)};img.src=url}
function importLayout(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const x=JSON.parse(r.result);Object.assign(state,x);controls();render()};r.readAsText(f)}
function start(){try{D=window.ML_DATA;if(!D)throw Error('embedded analysis data are missing');controls();render();$('status').textContent='500-repeat Mouse validation loaded · 16 editable panels · drag panels, text and resize handles · export matches the current SVG preview';}catch(e){$('status').textContent='Unable to load validation data: '+e.message}}
start();
