#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(data.table);library(ggplot2);library(dendextend);library(circlize);library(fmsb);library(pheatmap);library(ggrepel)})
base<-"C:/Users/53461/OneDrive/Documentos/Patch-seq_Mouse_Acb_MSN_T-type_Visualization/macaque_m";out<-file.path(base,"m18_tempfreeze_NPC5_HCK4_res2.3","panels_A_I");dir.create(out,recursive=TRUE,showWarnings=FALSE)
a<-fread(file.path(base,"m18_tempfreeze_NPC5_HCK4_res2.3","01_temp_frozen_assignments_126.csv"));s<-fread(file.path(base,"m18_adaptive_pca126","04_pca_scores.csv"));z<-fread(file.path(base,"m18_adaptive_pca126","02_transformed_z_117.csv"));ts<-fread(file.path(base,"m18_tempfreeze_NPC5_HCK4_res2.3","09_tSNE_optimized_coordinates.csv"));raw<-fread(file.path(base,"m18","01_raw_126.csv"))
cols<-c("1"="#1F77B4","2"="#D9A400","3"="#8C564B","4"="#E377C2");ts[,`:=`(cx=mean(tSNE1),cy=mean(tSNE2)),by=HC_K4];ts[,`:=`(x=cx+.85*(tSNE1-cx),y=cy+.85*(tSNE2-cy))]
savegg<-function(p,id,w=6,h=5){ggsave(file.path(out,paste0(id,".png")),p,width=w,height=h,dpi=500,bg="white");ggsave(file.path(out,paste0(id,".pdf")),p,width=w,height=h,bg="white")}

# A: HC-class t-SNE.
pA<-ggplot(ts,aes(x,y,color=factor(HC_K4),shape=concordant))+geom_point(size=1.65,stroke=.6,alpha=.92)+scale_color_manual(values=cols)+scale_shape_manual(values=c(`TRUE`=16,`FALSE`=4))+coord_equal()+labs(title="A",color="M class",shape="HC-GC concordant")+theme_void(base_size=12)+theme(plot.title=element_text(face="bold",size=12),legend.position="none",plot.margin=margin(8,8,8,8));savegg(pA,"A_HC_tSNE",4.2,4.2)

# B: one Ward.D2 tree, circular display, colored by fixed K=4 leaves.
x<-as.matrix(s[,paste0("PC",1:5),with=FALSE]);rownames(x)<-s$cell_label;hcobj<-hclust(dist(x),method="ward.D2");hc<-cutree(hcobj,4);den<-as.dendrogram(hcobj);labels_colors(den)<-cols[as.character(hc[labels(den)])]
den<-color_branches(den,k=4,col=unname(cols))
draw_tree<-function(){par(mar=c(1,1,2,1));circlize_dendrogram(den,labels=FALSE,dend_track_height=.82);title("B",adj=0,font.main=2)}
pdf(file.path(out,"B_WardD2_circular_tree.pdf"),width=7,height=7);draw_tree();dev.off()
png(file.path(out,"B_WardD2_circular_tree.png"),width=2800,height=2800,res=400);draw_tree();dev.off()

# C-F: class-specific radar profiles using eight interpretable raw features.
rf<-c("basal_dendrite_total_length","basal_dendrite_num_branches","basal_dendrite_max_branch_order","basal_dendrite_max_path_distance","basal_dendrite_max_euclidean_distance","basal_dendrite_mean_diameter","basal_dendrite_calculate_number_of_stems","soma_surface_area");labs<-c("Total length","Branches","Branch order","Path distance","Euclidean distance","Mean diameter","Stems","Soma area")
rr<-merge(a[,.(cell_label,HC_K4)],raw,by="cell_label");means<-rr[,lapply(.SD,mean),by=HC_K4,.SDcols=rf];scaled<-copy(means);for(f in rf){v<-means[[f]];scaled[[f]]<-(v-min(v))/(max(v)-min(v))}
for(k in 1:4){dat<-rbind(rep(1,8),rep(0,8),as.numeric(scaled[HC_K4==k,..rf]));colnames(dat)<-labs;id<-LETTERS[k+2];for(ext in c("pdf","png")){fn<-file.path(out,sprintf("%s_M%d_radar.%s",id,k,ext));if(ext=="pdf")pdf(fn,11,7) else png(fn,4400,2800,res=400);par(mar=c(3,4,4,4));radarchart(as.data.frame(dat),axistype=1,pcol=cols[as.character(k)],pfcol=adjustcolor(cols[as.character(k)],.25),plwd=3,cglcol="grey75",cglty=1,axislabcol="grey40",caxislabels=seq(0,1,.25),vlcex=.80);title(sprintf("%s | M%d morphology profile",id,k));dev.off()}}

# G: merged-GC t-SNE with class labels at medians.
cent<-ts[,.(x=median(x),y=median(y)),by=GC_merged_K4];pG<-ggplot(ts,aes(x,y,color=factor(GC_merged_K4),shape=concordant))+geom_point(size=1.65,stroke=.6,alpha=.92)+geom_text_repel(data=cent,aes(x=x,y=y,label=paste0("M",GC_merged_K4)),inherit.aes=FALSE,color=cols[as.character(cent$GC_merged_K4)],fontface="bold",size=3,box.padding=.2,show.legend=FALSE)+scale_color_manual(values=cols)+scale_shape_manual(values=c(`TRUE`=16,`FALSE`=4))+coord_equal()+labs(title="G")+theme_void(base_size=12)+theme(plot.title=element_text(face="bold",size=12),legend.position="none",plot.margin=margin(8,8,8,8));savegg(pG,"G_mergedGC_tSNE_labeled",4.2,4.2)

# H: fixed-HC by merged-GC confusion matrix.
ct<-a[,.(N=.N),by=.(HC_K4,GC_merged_K4)];ct<-merge(CJ(HC_K4=1:4,GC_merged_K4=1:4),ct,all.x=TRUE,by=c("HC_K4","GC_merged_K4"));ct[is.na(N),N:=0];ct[,row_percent:=100*N/sum(N),by=HC_K4]
pH<-ggplot(ct,aes(factor(GC_merged_K4),factor(HC_K4),fill=N))+geom_tile(color="white",linewidth=1)+geom_text(aes(label=sprintf("%d\n%.1f%%",N,row_percent)),size=5)+scale_fill_gradient(low="white",high="#2166AC")+coord_equal()+labs(title="H | Fixed HC versus consolidated GC",subtitle="Agreement 92.86%; adjusted Rand index 0.825",x="Merged GC class",y="Fixed HC class",fill="Cells")+theme_bw(base_size=12);savegg(pH,"H_HC_GC_confusion",6.5,5.8)

# I: all 18 transformed features, cells ordered by HC and within-class hierarchy.
a<-a[concordant==TRUE]
zmat<-as.matrix(z[,-1]);rownames(zmat)<-z$cell_label;group_ids<-lapply(1:4,function(k)a[HC_K4==k,cell_label]);set.seed(777);ord<-unlist(lapply(group_ids,sample));gaps<-cumsum(lengths(group_ids))[1:3];hm0<-t(zmat[ord,,drop=FALSE]);class_means<-sapply(group_ids,function(ids)rowMeans(t(zmat[ids,,drop=FALSE])));peak_group<-max.col(class_means,ties.method="first");feature_groups<-lapply(1:4,function(k)rownames(hm0)[peak_group==k]);feature_order<-unlist(lapply(feature_groups,function(ids){if(length(ids)>1) ids[hclust(dist(hm0[ids,,drop=FALSE]),method="ward.D2")$order] else ids}));row_gaps<-head(cumsum(lengths(feature_groups)),3);row_gaps<-row_gaps[row_gaps>0 & row_gaps<nrow(hm0)];hm<-hm0[feature_order,,drop=FALSE];mi<-match(ord,a$cell_label);ann<-data.frame(HC=factor(a$HC_K4[mi]),MergedGC=factor(a$GC_merged_K4[mi]),ROI=a$ROI[mi],`T class`=a$Subclass[mi],check.names=FALSE);rownames(ann)<-ord;anncols<-list(HC=cols,MergedGC=cols,ROI=c(Ca="#4C78A8",Pu="#F2CF5B",NAC="#59A14F"),`T class`=c("STR D1 MSN"="#E69F00","STR D2 MSN"="#56B4E9","STR Hybrid MSN"="#7A5195"));feature_map<-data.table(feature=rownames(hm0),peak_consensus_group=paste0("M",peak_group),M1_mean=class_means[,1],M2_mean=class_means[,2],M3_mean=class_means[,3],M4_mean=class_means[,4]);fwrite(feature_map,file.path(out,"I_feature_peak_consensus_group.csv"),bom=TRUE)
writeLines(c("order\tfeature\tpeak_consensus_group",sprintf("%02d\t%s\tM%d",seq_along(feature_order),feature_order,peak_group[match(feature_order,rownames(hm0))])),file.path(out,"I_morphology_Zscore_heatmap_metric_names.txt"),useBytes=TRUE)
writeLines(feature_order,file.path(out,"I_morphology_Zscore_heatmap_metric_names_only.txt"),useBytes=TRUE)
ann<-data.frame(ROI=a$ROI[mi],`T class`=a$Subclass[mi],`Consensus M`=factor(a$HC_K4[mi]),check.names=FALSE);rownames(ann)<-ord;m_cols<-c("1"="#1F77B4","2"="#D9A400","3"="#8C564B","4"="#E377C2");anncols<-list(`Consensus M`=m_cols,ROI=c(Ca="#246BB2",Pu="#3FA0E8",NAC="#7B1FA2"),`T class`=c("STR D1 MSN"="#D95F02","STR D2 MSN"="#008F7A","STR Hybrid MSN"="#6E7180"));heat_cols<-colorRampPalette(c("#A8156A","#0D0A01","#EECD39"))(101)
pheatmap(hm,cluster_rows=FALSE,cluster_cols=FALSE,gaps_row=row_gaps,gaps_col=gaps,show_colnames=FALSE,fontsize_row=6,border_color=NA,annotation_col=ann,annotation_colors=anncols,color=heat_cols,breaks=seq(-2.5,2.5,length.out=102),main="I | Diagonal consensus morphology modules (Z: -2.5 to 2.5)",filename=file.path(out,"I_morphology_Zscore_heatmap.pdf"),width=13,height=7)
pheatmap(hm,cluster_rows=FALSE,cluster_cols=FALSE,gaps_row=row_gaps,gaps_col=gaps,show_colnames=FALSE,fontsize_row=6,border_color=NA,annotation_col=ann,annotation_colors=anncols,color=heat_cols,breaks=seq(-2.5,2.5,length.out=102),main="I | Diagonal consensus morphology modules (Z: -2.5 to 2.5)",filename=file.path(out,"I_morphology_Zscore_heatmap.png"),width=13,height=7)
fwrite(scaled,file.path(out,"radar_class_scaled_means.csv"),bom=TRUE);fwrite(ct,file.path(out,"H_confusion_values.csv"),bom=TRUE);cat("Created panels A-I in",out,"\n")
