#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(data.table);library(Rtsne);library(cluster);library(ggplot2)})
base<-"C:/Users/53461/OneDrive/Documentos/Patch-seq_Mouse_Acb_MSN_T-type_Visualization/macaque_m";out<-file.path(base,"m18_tempfreeze_NPC5_HCK4_res2.3")
s<-fread(file.path(base,"m18_adaptive_pca126","04_pca_scores.csv"));a<-fread(file.path(out,"01_temp_frozen_assignments_126.csv"));x<-as.matrix(s[,paste0("PC",1:5),with=FALSE]);rownames(x)<-s$cell_label;hc<-a$HC_K4[match(s$cell_label,a$cell_label)]
knn<-function(x,k=10)t(apply(as.matrix(dist(x)),1,function(v)order(v)[2:(k+1)]));ref<-knn(x);runs<-list();coords<-list();i<-0L
for(perp in c(10,15,20,25,30))for(seed in 777:781){set.seed(seed);f<-Rtsne(x,dims=2,perplexity=perp,theta=0,max_iter=2000,pca=FALSE,check_duplicates=FALSE,verbose=FALSE);i<-i+1L;y<-f$Y;nb<-knn(y);pres<-mean(vapply(seq_len(nrow(x)),function(j)length(intersect(ref[j,],nb[j,]))/10,numeric(1)));sil<-mean(silhouette(hc,dist(y))[,3]);runs[[i]]<-data.table(perplexity=perp,seed=seed,neighbor_preservation=pres,HC_silhouette=sil,KL=f$itercosts[length(f$itercosts)]);coords[[i]]<-y}
r<-rbindlist(runs);r[,score:=rank(neighbor_preservation)+rank(HC_silhouette)];best<-which.max(r$score);b<-r[best];d<-merge(data.table(cell_label=s$cell_label,tSNE1=coords[[best]][,1],tSNE2=coords[[best]][,2]),a[,.(cell_label,HC_K4,GC_merged_K4,concordant)],by="cell_label");fwrite(r[order(-score)],file.path(out,"08_tSNE_parameter_scan.csv"),bom=TRUE);fwrite(d,file.path(out,"09_tSNE_optimized_coordinates.csv"),bom=TRUE)
long<-rbind(d[,.(cell_label,tSNE1,tSNE2,class=factor(HC_K4),concordant,panel="Fixed HC K=4")],d[,.(cell_label,tSNE1,tSNE2,class=factor(GC_merged_K4),concordant,panel="Merged GC K=4")]);cols<-c("1"="#0072B2","2"="#D55E00","3"="#009E73","4"="#CC79A7")
p<-ggplot(long,aes(tSNE1,tSNE2,color=class,shape=concordant))+geom_point(size=3,alpha=.92)+facet_wrap(~panel,nrow=1)+scale_color_manual(values=cols)+scale_shape_manual(values=c(`TRUE`=16,`FALSE`=4))+coord_equal()+labs(title="Optimized t-SNE of temporary macaque MSN morphology classes",subtitle=sprintf("PC1-PC5 | perplexity=%d, seed=%d | 10-NN preservation=%.3f, HC silhouette=%.3f",b$perplexity,b$seed,b$neighbor_preservation,b$HC_silhouette),x="t-SNE 1",y="t-SNE 2",color="M class",shape="HC-GC concordant")+theme_classic(base_size=13)+theme(axis.text=element_blank(),axis.ticks=element_blank(),legend.position="bottom",legend.box="horizontal",panel.spacing=unit(1,"lines"))
ggsave(file.path(out,"11_tSNE_optimized_large_axes.png"),p,width=14,height=7,dpi=500,bg="white");print(r[order(-score)][1:10])
